DROP INDEX IF EXISTS idx_logs_commit_hash;
DROP INDEX IF EXISTS idx_logs_request_id;
DROP INDEX IF EXISTS idx_logs_environment;
DROP INDEX IF EXISTS idx_logs_exception_class;
DROP INDEX IF EXISTS idx_logs_error_fingerprint;
DROP INDEX IF EXISTS idx_logs_source_file;
ALTER TABLE logs DROP COLUMN commit_hash;
ALTER TABLE logs DROP COLUMN request_id;
ALTER TABLE logs DROP COLUMN exception_class;
ALTER TABLE logs DROP COLUMN error_fingerprint;
ALTER TABLE logs DROP COLUMN source_file;
ALTER TABLE logs DROP COLUMN source_line;
