-- Watcher severity levels
CREATE TYPE watcher_severity AS ENUM ('info', 'warning', 'critical');

-- Watcher status
CREATE TYPE watcher_status AS ENUM ('active', 'paused', 'error');

-- Core watcher definitions
CREATE TABLE watchers (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title            TEXT NOT NULL,
    description      TEXT NOT NULL,
    severity         watcher_severity NOT NULL DEFAULT 'warning',
    filters          JSONB NOT NULL DEFAULT '{}',
    interval_seconds INT NOT NULL DEFAULT 300,
    status           watcher_status NOT NULL DEFAULT 'active',
    notify           JSONB NOT NULL DEFAULT '["dashboard"]',
    last_run_at      TIMESTAMPTZ,
    next_run_at      TIMESTAMPTZ,
    last_error       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Watcher execution history
CREATE TABLE watcher_runs (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    watcher_id  UUID NOT NULL REFERENCES watchers(id) ON DELETE CASCADE,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    status      TEXT NOT NULL DEFAULT 'running',
    summary     TEXT,
    details     JSONB,
    has_alert   BOOLEAN NOT NULL DEFAULT false,
    error       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_watcher_runs_watcher_id ON watcher_runs(watcher_id, created_at DESC);

-- Alerts generated by watchers
CREATE TABLE alerts (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    watcher_id UUID REFERENCES watchers(id) ON DELETE SET NULL,
    run_id     UUID REFERENCES watcher_runs(id) ON DELETE SET NULL,
    title      TEXT NOT NULL,
    summary    TEXT NOT NULL,
    severity   watcher_severity NOT NULL DEFAULT 'warning',
    details    JSONB,
    read       BOOLEAN NOT NULL DEFAULT false,
    dismissed  BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_alerts_created_at ON alerts(created_at DESC);
CREATE INDEX idx_alerts_unread ON alerts(created_at DESC) WHERE read = false AND dismissed = false;
