package auth

import (
	"fmt"
	"net/http"
	"strings"
)

// handleConnectScript serves a self-contained bash script that authenticates
// and creates .mcp.json. The user runs it with:
//
//	curl -s https://server:8080/connect | bash
//
// The script prompts for email/password, calls POST /api/auth/connect,
// and writes .mcp.json + .gitignore in the current directory.
func (h *handler) handleConnectScript(w http.ResponseWriter, r *http.Request) {
	// Infer server URL from the request
	scheme := "https"
	if r.TLS == nil && !strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https") {
		scheme = "http"
	}
	serverURL := fmt.Sprintf("%s://%s", scheme, r.Host)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")

	fmt.Fprintf(w, `#!/bin/bash
set -euo pipefail

# OpenTrace — connect your project
# Generated by %s

SERVER="%s"

echo ""
echo "  OpenTrace — connect your project"
echo "  Server: ${SERVER}"
echo ""

# Check if .mcp.json already exists
if [ -f .mcp.json ]; then
  echo "  .mcp.json already exists in this directory."
  read -r -p "  Overwrite? [y/N] " CONFIRM
  if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "  Aborted."
    exit 0
  fi
fi

# Check server health
echo -n "  Checking server... "
HEALTH=$(curl -sf "${SERVER}/api/auth/connect" 2>/dev/null) || {
  echo "FAILED"
  echo "  Cannot reach ${SERVER}"
  echo "  Check the URL and try again."
  exit 1
}
echo "ok"

# Check if setup is needed
NEEDS_SETUP=$(echo "$HEALTH" | grep -o '"needs_setup":true' || true)
if [ -n "$NEEDS_SETUP" ]; then
  echo ""
  echo "  No accounts exist yet. Set up your admin account."
  echo ""
fi

# Prompt for credentials
read -r -p "  Email: " EMAIL
if [ -z "$EMAIL" ]; then
  echo "  Email is required."
  exit 1
fi

# Read password without echo
if [ -t 0 ]; then
  stty -echo 2>/dev/null || true
  read -r -p "  Password: " PASS
  stty echo 2>/dev/null || true
  echo ""
else
  read -r -p "  Password: " PASS
fi

if [ -z "$PASS" ]; then
  echo "  Password is required."
  exit 1
fi

# Confirm password for new admin
if [ -n "$NEEDS_SETUP" ]; then
  stty -echo 2>/dev/null || true
  read -r -p "  Confirm:  " PASS2
  stty echo 2>/dev/null || true
  echo ""
  if [ "$PASS" != "$PASS2" ]; then
    echo "  Passwords do not match."
    exit 1
  fi
  if [ ${#PASS} -lt 12 ]; then
    echo "  Password must be at least 12 characters."
    exit 1
  fi
fi

# Authenticate
echo -n "  Authenticating... "
RESPONSE=$(curl -sf -X POST "${SERVER}/api/auth/connect" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"${EMAIL}\",\"password\":\"${PASS}\"}" 2>/dev/null) || {
  echo "FAILED"
  echo "  Invalid credentials."
  exit 1
}

# Extract token
TOKEN=$(echo "$RESPONSE" | grep -o '"token":"[^"]*"' | head -1 | cut -d'"' -f4)
if [ -z "$TOKEN" ]; then
  echo "FAILED"
  echo "  No token returned. Check your credentials."
  exit 1
fi

# Check if admin was created
if echo "$RESPONSE" | grep -q '"created_admin":true'; then
  echo "admin account created"
else
  echo "ok"
fi

# Determine MCP endpoint path
MCP_URL="${SERVER}/mcp/sse"

# Write .mcp.json
cat > .mcp.json << MCPEOF
{
  "mcpServers": {
    "opentrace": {
      "type": "sse",
      "url": "${MCP_URL}",
      "headers": {
        "Authorization": "Bearer ${TOKEN}"
      }
    }
  }
}
MCPEOF

echo "  ✓ .mcp.json created"

# Add to .gitignore
if [ -d .git ]; then
  if [ ! -f .gitignore ]; then
    echo ".mcp.json" > .gitignore
    echo "  ✓ .mcp.json added to .gitignore"
  elif ! grep -q "^\.mcp\.json$" .gitignore 2>/dev/null; then
    echo "" >> .gitignore
    echo ".mcp.json" >> .gitignore
    echo "  ✓ .mcp.json added to .gitignore"
  fi
fi

echo ""
echo "  Done. Open Claude Code in this project — OpenTrace is connected."
echo ""
`, serverURL, serverURL)
}
