package store

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// ErrNotFound is returned when a requested resource does not exist.
var ErrNotFound = errors.New("not found")

// DataSourceStore defines CRUD operations for data sources.
type DataSourceStore interface {
	Create(ctx context.Context, params CreateDataSourceParams) (*DataSource, error)
	GetByID(ctx context.Context, id uuid.UUID) (*DataSource, error)
	List(ctx context.Context) ([]DataSource, error)
	Update(ctx context.Context, id uuid.UUID, params UpdateDataSourceParams) (*DataSource, error)
	Delete(ctx context.Context, id uuid.UUID) error
}

// LogStore defines operations for log ingestion and search.
type LogStore interface {
	BatchInsert(ctx context.Context, entries []LogEntry) (int, error)
	Search(ctx context.Context, params LogSearchParams) ([]LogEntry, error)
}

// WatcherStore manages watcher definitions.
type WatcherStore interface {
	Create(ctx context.Context, params CreateWatcherParams) (*Watcher, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Watcher, error)
	List(ctx context.Context) ([]Watcher, error)
	Update(ctx context.Context, id uuid.UUID, params UpdateWatcherParams) (*Watcher, error)
	UpdateStatus(ctx context.Context, id uuid.UUID, status WatcherStatus) (*Watcher, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetDueWatchers(ctx context.Context) ([]Watcher, error)
	UpdateRunTime(ctx context.Context, id uuid.UUID, lastRun, nextRun time.Time) error
}

// WatcherRunStore manages watcher execution history.
type WatcherRunStore interface {
	Create(ctx context.Context, watcherID uuid.UUID) (*WatcherRun, error)
	Complete(ctx context.Context, id uuid.UUID, summary string, details any, hasAlert bool) error
	Fail(ctx context.Context, id uuid.UUID, errMsg string) error
	List(ctx context.Context, watcherID uuid.UUID, limit int) ([]WatcherRun, error)
	GetByID(ctx context.Context, id uuid.UUID) (*WatcherRun, error)
}

// AlertStore manages alerts generated by watchers.
type AlertStore interface {
	Create(ctx context.Context, params CreateAlertParams) (*Alert, error)
	List(ctx context.Context, params ListAlertParams) ([]Alert, error)
	CountUnread(ctx context.Context) (int, error)
	MarkRead(ctx context.Context, id uuid.UUID) error
	Dismiss(ctx context.Context, id uuid.UUID) error
}
