package store

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// ErrNotFound is returned when a requested resource does not exist.
var ErrNotFound = errors.New("not found")

// DataSourceStore defines CRUD operations for data sources.
type DataSourceStore interface {
	Create(ctx context.Context, params CreateDataSourceParams) (*DataSource, error)
	GetByID(ctx context.Context, id uuid.UUID) (*DataSource, error)
	List(ctx context.Context, params ListDataSourceParams) ([]DataSource, error)
	Update(ctx context.Context, id uuid.UUID, params UpdateDataSourceParams) (*DataSource, error)
	Delete(ctx context.Context, id uuid.UUID) error
}

// LogStore defines operations for log ingestion and search.
type LogStore interface {
	BatchInsert(ctx context.Context, entries []LogEntry) (int, error)
	Search(ctx context.Context, params LogSearchParams) ([]LogEntry, error)
	Prune(ctx context.Context, olderThan time.Duration) (int64, error)
	CountByLevel(ctx context.Context, params LogCountParams) (map[string]int, error)
	CountByService(ctx context.Context, params LogCountParams) ([]ServiceLogCount, error)
	DistinctValues(ctx context.Context, field string, params LogCountParams) ([]string, error)
	MetadataKeys(ctx context.Context, params LogCountParams) ([]string, error)
	GetByID(ctx context.Context, id int64) (*LogEntry, error)
	// Batch deduplication
	RecordBatch(ctx context.Context, batchID string, logCount int) error
	GetBatch(ctx context.Context, batchID string) (*BatchRecord, error)
	PruneBatches(ctx context.Context, olderThan time.Duration) (int64, error)
}

// BatchRecord tracks a processed batch for deduplication.
type BatchRecord struct {
	BatchID    string
	LogCount   int
	ReceivedAt time.Time
}

// UpdateAdaptiveParams defines the input for updating adaptive scheduling state.
type UpdateAdaptiveParams struct {
	AdaptiveState        AdaptiveState
	ConsecutiveCleanRuns int
	ConsecutiveErrors    int
	EscalatedAt          *time.Time
	TimeRange            string // current effective time_range
	BaseTimeRange        string // original time_range (set once on first escalation)
}

// WatcherStore manages watcher definitions.
type WatcherStore interface {
	Create(ctx context.Context, params CreateWatcherParams) (*Watcher, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Watcher, error)
	List(ctx context.Context, params ListWatcherParams) ([]Watcher, error)
	Update(ctx context.Context, id uuid.UUID, params UpdateWatcherParams) (*Watcher, error)
	UpdateStatus(ctx context.Context, id uuid.UUID, status WatcherStatus) (*Watcher, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetDueWatchers(ctx context.Context) ([]Watcher, error)
	UpdateRunTime(ctx context.Context, id uuid.UUID, lastRun, nextRun time.Time) error
	UpdateAdaptiveState(ctx context.Context, id uuid.UUID, params UpdateAdaptiveParams) error
	ResumeWatcher(ctx context.Context, id uuid.UUID) error
}

// CountRunParams defines filters for counting watcher runs in a time period.
type CountRunParams struct {
	Since     time.Time
	Until     time.Time
	Status    string     // optional: "completed", "failed", "error"
	WatcherID *uuid.UUID // optional
}

// WatcherRunStore manages watcher execution history.
type WatcherRunStore interface {
	Create(ctx context.Context, watcherID uuid.UUID) (*WatcherRun, error)
	Complete(ctx context.Context, id uuid.UUID, summary string, details any, hasAlert bool) error
	Fail(ctx context.Context, id uuid.UUID, errMsg string) error
	FailStaleRuns(ctx context.Context, olderThan time.Duration) (int, error)
	List(ctx context.Context, watcherID uuid.UUID, limit int) ([]WatcherRun, error)
	ListWithFilter(ctx context.Context, watcherID uuid.UUID, limit int, status string) ([]WatcherRun, error)
	ListRecentFailed(ctx context.Context, limit int) ([]WatcherRun, error)
	GetByID(ctx context.Context, id uuid.UUID) (*WatcherRun, error)
	Prune(ctx context.Context, olderThan time.Duration) (int64, error)
	CountRuns(ctx context.Context, params CountRunParams) (int, error)
}

// AlertStore manages alerts generated by watchers.
type AlertStore interface {
	Create(ctx context.Context, params CreateAlertParams) (*Alert, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Alert, error)
	List(ctx context.Context, params ListAlertParams) ([]Alert, error)
	CountUnread(ctx context.Context) (int, error)
	CountTotal(ctx context.Context) (int, error)
	CountBySeverity(ctx context.Context, since, until time.Time) (map[string]int, error)
	MarkRead(ctx context.Context, id uuid.UUID) error
	MarkAllRead(ctx context.Context) error
	Dismiss(ctx context.Context, id uuid.UUID, reason string) error
	DismissAll(ctx context.Context) error
	Snooze(ctx context.Context, id uuid.UUID, until time.Time) error
	Unsnooze(ctx context.Context, id uuid.UUID) error
	WatcherAlertStats(ctx context.Context, watcherID uuid.UUID, since time.Time) (*WatcherEffectiveness, error)
	Prune(ctx context.Context, olderThan time.Duration) (int64, error)
}

// ServerStore manages monitored server registrations.
type ServerStore interface {
	Register(ctx context.Context, params RegisterServerParams) (*Server, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Server, error)
	List(ctx context.Context) ([]Server, error)
	UpdateHeartbeat(ctx context.Context, id uuid.UUID) error
	Delete(ctx context.Context, id uuid.UUID) error
	MarkStaleOffline(ctx context.Context, threshold time.Duration) (int, error)
}

// MetricStore manages time-series metric data for servers.
type MetricStore interface {
	BatchInsert(ctx context.Context, serverID uuid.UUID, ts time.Time, samples []MetricSample) (int, error)
	Query(ctx context.Context, params MetricQuery) ([]MetricPoint, error)
	LatestByServer(ctx context.Context, serverID uuid.UUID) ([]MetricPoint, error)
	Prune(ctx context.Context, olderThan time.Duration) (int64, error)
}

// ErrEmailTaken is returned when a user attempts to register with an email already in use.
var ErrEmailTaken = errors.New("email already taken")

// ErrLastAdmin is returned when attempting to demote or delete the last admin user.
var ErrLastAdmin = errors.New("cannot remove the last admin")

// UserStore manages user accounts.
type UserStore interface {
	Create(ctx context.Context, params CreateUserParams) (*User, error)
	GetByID(ctx context.Context, id string) (*User, error)
	GetByEmail(ctx context.Context, email string) (*User, error)
	GetByMCPToken(ctx context.Context, token string) (*User, error)
	List(ctx context.Context) ([]User, error)
	Update(ctx context.Context, id string, params UpdateUserParams) (*User, error)
	UpdatePassword(ctx context.Context, id string, passwordHash string) error
	UpdateMCPToken(ctx context.Context, id string, token string) error
	Delete(ctx context.Context, id string) error
	Count(ctx context.Context) (int, error)
}

// SessionStore manages browser sessions.
type SessionStore interface {
	Create(ctx context.Context, userID string, token string, expiresAt time.Time) (*Session, error)
	GetByToken(ctx context.Context, token string) (*Session, error)
	Delete(ctx context.Context, id string) error
	DeleteExpired(ctx context.Context) (int, error)
	DeleteAllForUser(ctx context.Context, userID string) error
}

// RetentionSettings holds data retention configuration.
type RetentionSettings struct {
	RetentionDays int `json:"retention_days"`
}

// SettingsStore manages application settings stored in app_config.
type SettingsStore interface {
	GetRetention(ctx context.Context) (*RetentionSettings, error)
	SetRetention(ctx context.Context, settings RetentionSettings) error
	GetAPIKey(ctx context.Context) (string, error)
	SetAPIKey(ctx context.Context, key string) error
	GetAutoUpdate(ctx context.Context) (bool, error)
	SetAutoUpdate(ctx context.Context, enabled bool) error
}

// MCPActivityStore tracks MCP tool calls and connection events.
type MCPActivityStore interface {
	Log(ctx context.Context, params LogMCPActivityParams) error
	Stats(ctx context.Context) (*MCPActivityStats, error)
	Recent(ctx context.Context, limit int) ([]MCPActivityEvent, error)
	Prune(ctx context.Context, olderThan time.Duration) (int64, error)
}

// AuditStore tracks admin actions for security audit trail.
type AuditStore interface {
	Log(ctx context.Context, params LogAuditParams) error
	Recent(ctx context.Context, limit int) ([]AuditEntry, error)
	Prune(ctx context.Context, olderThan time.Duration) (int64, error)
}

// AlertGroupStore manages alert groups (incidents).
type AlertGroupStore interface {
	Create(ctx context.Context, params CreateAlertGroupParams) (*AlertGroup, error)
	GetByID(ctx context.Context, id string) (*AlertGroup, error)
	List(ctx context.Context, status string) ([]AlertGroup, error)
	Update(ctx context.Context, id string, params UpdateAlertGroupParams) error
	AddAlerts(ctx context.Context, groupID string, alertIDs []string) error
	RemoveAlert(ctx context.Context, groupID string, alertID string) error
	GetGroupForAlert(ctx context.Context, alertID string) (*AlertGroup, error)
	Delete(ctx context.Context, id string) error
	AutoCorrelate(ctx context.Context, windowMinutes int) ([]AlertGroup, error)
}
