package store

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// ErrNotFound is returned when a requested resource does not exist.
var ErrNotFound = errors.New("not found")

// DataSourceStore defines CRUD operations for data sources.
type DataSourceStore interface {
	Create(ctx context.Context, params CreateDataSourceParams) (*DataSource, error)
	GetByID(ctx context.Context, id uuid.UUID) (*DataSource, error)
	List(ctx context.Context) ([]DataSource, error)
	Update(ctx context.Context, id uuid.UUID, params UpdateDataSourceParams) (*DataSource, error)
	Delete(ctx context.Context, id uuid.UUID) error
}

// LogStore defines operations for log ingestion and search.
type LogStore interface {
	BatchInsert(ctx context.Context, entries []LogEntry) (int, error)
	Search(ctx context.Context, params LogSearchParams) ([]LogEntry, error)
}

// ChatStore defines operations for chat persistence.
type ChatStore interface {
	CreateChat(ctx context.Context, title string) (*Chat, error)
	GetChat(ctx context.Context, id uuid.UUID) (*Chat, error)
	ListChats(ctx context.Context) ([]Chat, error)
	DeleteChat(ctx context.Context, id uuid.UUID) error
	UpdateChatTitle(ctx context.Context, id uuid.UUID, title string) error
	AddMessage(ctx context.Context, msg Message) error
	GetMessages(ctx context.Context, chatID uuid.UUID) ([]Message, error)
}

// MemoryStore defines operations for the agent's cross-conversation knowledge base.
type MemoryStore interface {
	AddMemory(ctx context.Context, category, content, source string) error
	ListMemories(ctx context.Context, category string) ([]MemoryEntry, error)
	SearchMemories(ctx context.Context, query string) ([]MemoryEntry, error)
	DeleteMemory(ctx context.Context, id uuid.UUID) error
}

// EmbeddingStore defines operations for code embedding storage and search.
type EmbeddingStore interface {
	UpsertChunks(ctx context.Context, chunks []CodeChunk) error
	Search(ctx context.Context, embedding []float64, limit int) ([]CodeSearchResult, error)
	DeleteByPath(ctx context.Context, filePath string) error
	DeleteAll(ctx context.Context) error
}

// WatcherStore manages watcher definitions.
type WatcherStore interface {
	Create(ctx context.Context, params CreateWatcherParams) (*Watcher, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Watcher, error)
	List(ctx context.Context) ([]Watcher, error)
	Update(ctx context.Context, id uuid.UUID, params UpdateWatcherParams) (*Watcher, error)
	UpdateStatus(ctx context.Context, id uuid.UUID, status WatcherStatus) (*Watcher, error)
	Delete(ctx context.Context, id uuid.UUID) error
	GetDueWatchers(ctx context.Context) ([]Watcher, error)
	UpdateRunTime(ctx context.Context, id uuid.UUID, lastRun, nextRun time.Time) error
}

// WatcherRunStore manages watcher execution history.
type WatcherRunStore interface {
	Create(ctx context.Context, watcherID uuid.UUID) (*WatcherRun, error)
	Complete(ctx context.Context, id uuid.UUID, summary string, details any, hasAlert bool) error
	Fail(ctx context.Context, id uuid.UUID, errMsg string) error
	List(ctx context.Context, watcherID uuid.UUID, limit int) ([]WatcherRun, error)
	GetByID(ctx context.Context, id uuid.UUID) (*WatcherRun, error)
}

// AlertStore manages alerts generated by watchers.
type AlertStore interface {
	Create(ctx context.Context, params CreateAlertParams) (*Alert, error)
	List(ctx context.Context, params ListAlertParams) ([]Alert, error)
	CountUnread(ctx context.Context) (int, error)
	MarkRead(ctx context.Context, id uuid.UUID) error
	Dismiss(ctx context.Context, id uuid.UUID) error
}
