package store

import "time"

// WatchMetric identifies what the watch measures.
type WatchMetric string

const (
	WatchMetricErrorRate    WatchMetric = "error_rate"
	WatchMetricResponseTime WatchMetric = "response_time"
	WatchMetricP95Response  WatchMetric = "p95_response"
	WatchMetricLogCount     WatchMetric = "log_count"
	WatchMetricErrorCount   WatchMetric = "error_count"
	WatchMetricHeartbeat    WatchMetric = "heartbeat"
	WatchMetricSQLCount     WatchMetric = "sql_count"
	WatchMetricCacheHitRate WatchMetric = "cache_hit_rate"
)

// WatchOperator defines comparison operators for watches.
type WatchOperator string

const (
	WatchOpGreaterThan      WatchOperator = "gt"
	WatchOpGreaterThanEqual WatchOperator = "gte"
	WatchOpLessThan         WatchOperator = "lt"
	WatchOpLessThanEqual    WatchOperator = "lte"
	WatchOpEqual            WatchOperator = "eq"
	WatchOpNotEqual         WatchOperator = "neq"
)

// WatchStatus represents the lifecycle state of a watch.
type WatchStatus string

const (
	WatchStatusActive    WatchStatus = "active"
	WatchStatusTriggered WatchStatus = "triggered"
	WatchStatusResolved  WatchStatus = "resolved"
	WatchStatusExpired   WatchStatus = "expired"
)

// WatchUrgency represents alert urgency for a watch.
type WatchUrgency string

const (
	WatchUrgencyLow      WatchUrgency = "low"
	WatchUrgencyNormal   WatchUrgency = "normal"
	WatchUrgencyHigh     WatchUrgency = "high"
	WatchUrgencyCritical WatchUrgency = "critical"
)

// Watch represents a simplified metric threshold monitor.
type Watch struct {
	ID                  string         `json:"id"`
	Metric              WatchMetric    `json:"metric"`
	Operator            WatchOperator  `json:"operator"`
	Threshold           float64        `json:"threshold"`
	Service             string         `json:"service,omitempty"`
	Endpoint            string         `json:"endpoint,omitempty"`
	Environment         string         `json:"environment,omitempty"`
	CommitHash          string         `json:"commit_hash,omitempty"`
	Duration            string         `json:"duration"`
	Urgency             WatchUrgency   `json:"urgency"`
	CheckInterval       string         `json:"check_interval"`
	BaselineWindow      string         `json:"baseline_window"`
	MinConsecutive      int            `json:"min_consecutive"`
	Status              WatchStatus    `json:"status"`
	BaselineJSON        *WatchBaseline `json:"baseline,omitempty"`
	ConsecutiveBreaches int            `json:"consecutive_breaches"`
	CurrentValue        *float64       `json:"current_value,omitempty"`
	ExpiresAt           *time.Time     `json:"expires_at,omitempty"`
	CreatedBy           string         `json:"created_by,omitempty"`
	SessionID           string         `json:"session_id,omitempty"`
	LastCheckedAt       *time.Time     `json:"last_checked_at,omitempty"`
	NextCheckAt         *time.Time     `json:"next_check_at,omitempty"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

// CreateWatchParams defines the input for creating a watch.
type CreateWatchParams struct {
	Metric         WatchMetric   `json:"metric"`
	Operator       WatchOperator `json:"operator"`
	Threshold      float64       `json:"threshold"`
	Service        string        `json:"service,omitempty"`
	Endpoint       string        `json:"endpoint,omitempty"`
	Environment    string        `json:"environment,omitempty"`
	CommitHash     string        `json:"commit_hash,omitempty"`
	Duration       string        `json:"duration,omitempty"`
	Urgency        WatchUrgency  `json:"urgency,omitempty"`
	CheckInterval  string        `json:"check_interval,omitempty"`
	BaselineWindow string        `json:"baseline_window,omitempty"`
	MinConsecutive int           `json:"min_consecutive,omitempty"`
	CreatedBy      string        `json:"created_by,omitempty"`
	SessionID      string        `json:"session_id,omitempty"`
}

// ListWatchParams defines filters for listing watches.
type ListWatchParams struct {
	Status    WatchStatus `json:"status,omitempty"`
	Service   string      `json:"service,omitempty"`
	SessionID string      `json:"session_id,omitempty"`
	Limit     int         `json:"limit,omitempty"`
	Offset    int         `json:"offset,omitempty"`
}

// WatchRun represents a single evaluation of a watch.
type WatchRun struct {
	ID           string     `json:"id"`
	WatchID      string     `json:"watch_id"`
	Status       string     `json:"status"`
	MetricValue  *float64   `json:"metric_value,omitempty"`
	Breached     bool       `json:"breached"`
	Summary      string     `json:"summary,omitempty"`
	ErrorMessage string     `json:"error_message,omitempty"`
	StartedAt    time.Time  `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
}

// WatchAlert represents an alert generated by a watch breach.
type WatchAlert struct {
	ID             string               `json:"id"`
	WatchID        string               `json:"watch_id"`
	RunID          string               `json:"run_id,omitempty"`
	Urgency        WatchUrgency         `json:"urgency"`
	Summary        string               `json:"summary"`
	TriggerMetric  string               `json:"trigger_metric"`
	TriggerValue   float64              `json:"trigger_value"`
	ThresholdValue float64              `json:"threshold_value"`
	EvidenceJSON   *WatchEvidenceBundle `json:"evidence,omitempty"`
	Status         string               `json:"status"`
	DismissReason  string               `json:"dismiss_reason,omitempty"`
	CreatedAt      time.Time            `json:"created_at"`
}

// CreateWatchAlertParams defines the input for creating a watch alert.
type CreateWatchAlertParams struct {
	WatchID        string               `json:"watch_id"`
	RunID          string               `json:"run_id,omitempty"`
	Urgency        WatchUrgency         `json:"urgency"`
	Summary        string               `json:"summary"`
	TriggerMetric  string               `json:"trigger_metric"`
	TriggerValue   float64              `json:"trigger_value"`
	ThresholdValue float64              `json:"threshold_value"`
	Evidence       *WatchEvidenceBundle `json:"evidence,omitempty"`
}

// WatchBaseline holds a snapshot of baseline metrics at watch creation time.
type WatchBaseline struct {
	ErrorRate        float64                 `json:"error_rate"`
	AvgResponseMs    float64                 `json:"avg_response_ms"`
	P95ResponseMs    float64                 `json:"p95_response_ms"`
	LogCount         int                     `json:"log_count"`
	ErrorCount       int                     `json:"error_count"`
	SQLCount         float64                 `json:"sql_count"`
	CacheHitRate     float64                 `json:"cache_hit_rate"`
	ExceptionClasses []string                `json:"exception_classes,omitempty"`
	Endpoints        []WatchEndpointBaseline `json:"endpoints,omitempty"`
	CapturedAt       time.Time               `json:"captured_at"`
	WindowDuration   string                  `json:"window_duration"`
}

// WatchEndpointBaseline holds per-endpoint baseline stats.
type WatchEndpointBaseline struct {
	Path          string  `json:"path"`
	AvgDurationMs float64 `json:"avg_duration_ms"`
	AvgSQLCount   float64 `json:"avg_sql_count"`
	RequestCount  int     `json:"request_count"`
}

// WatchEvidenceBundle contains all evidence collected when an alert fires.
type WatchEvidenceBundle struct {
	RecentErrors      []WatchEvidenceError `json:"recent_errors,omitempty"`
	NewErrors         []WatchEvidenceError `json:"new_errors,omitempty"`
	AffectedEndpoints []WatchEndpointDelta `json:"affected_endpoints,omitempty"`
	RelevantLogs      []WatchEvidenceLog   `json:"relevant_logs,omitempty"`
	Timeline          []WatchTimelineEvent `json:"timeline,omitempty"`
	BaselineDiff      *WatchBaselineDiff   `json:"baseline_diff,omitempty"`
	SourceFiles       []string             `json:"source_files,omitempty"`
	TraceIDs          []string             `json:"trace_ids,omitempty"`
}

// WatchEvidenceLog represents a relevant log entry in evidence.
type WatchEvidenceLog struct {
	Timestamp time.Time `json:"timestamp"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	Service   string    `json:"service,omitempty"`
	TraceID   string    `json:"trace_id,omitempty"`
}

// WatchEvidenceError represents an error found during investigation.
type WatchEvidenceError struct {
	ExceptionClass string `json:"exception_class"`
	Message        string `json:"message"`
	Count          int    `json:"count"`
	IsNew          bool   `json:"is_new"`
}

// WatchEndpointDelta shows how an endpoint changed vs baseline.
type WatchEndpointDelta struct {
	Path               string  `json:"path"`
	CurrentDurationMs  float64 `json:"current_duration_ms"`
	BaselineDurationMs float64 `json:"baseline_duration_ms"`
	DeltaPct           float64 `json:"delta_pct"`
}

// WatchBaselineDiff shows overall metric drift from baseline.
type WatchBaselineDiff struct {
	MetricName    string  `json:"metric_name"`
	BaselineValue float64 `json:"baseline_value"`
	CurrentValue  float64 `json:"current_value"`
	DeltaPct      float64 `json:"delta_pct"`
}

// WatchTimelineEvent marks a point in the alert timeline.
type WatchTimelineEvent struct {
	Timestamp time.Time `json:"timestamp"`
	Event     string    `json:"event"`
	Value     *float64  `json:"value,omitempty"`
}
