// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_notes.sql

package db

import (
	"context"
)

const deleteAgentNote = `-- name: DeleteAgentNote :execrows
DELETE FROM agent_notes
WHERE entity_type = ?1 AND entity_id = ?2
`

type DeleteAgentNoteParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) DeleteAgentNote(ctx context.Context, arg DeleteAgentNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentNote, arg.EntityType, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentNote = `-- name: GetAgentNote :one
SELECT id, entity_type, entity_id, note, created_at, updated_at
FROM agent_notes
WHERE entity_type = ?1 AND entity_id = ?2
`

type GetAgentNoteParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) GetAgentNote(ctx context.Context, arg GetAgentNoteParams) (AgentNote, error) {
	row := q.db.QueryRowContext(ctx, getAgentNote, arg.EntityType, arg.EntityID)
	var i AgentNote
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentNotesByType = `-- name: ListAgentNotesByType :many
SELECT id, entity_type, entity_id, note, created_at, updated_at
FROM agent_notes
WHERE entity_type = ?1
ORDER BY updated_at DESC
`

func (q *Queries) ListAgentNotesByType(ctx context.Context, entityType string) ([]AgentNote, error) {
	rows, err := q.db.QueryContext(ctx, listAgentNotesByType, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentNote{}
	for rows.Next() {
		var i AgentNote
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgentNotes = `-- name: ListAllAgentNotes :many
SELECT id, entity_type, entity_id, note, created_at, updated_at
FROM agent_notes
ORDER BY updated_at DESC
`

func (q *Queries) ListAllAgentNotes(ctx context.Context) ([]AgentNote, error) {
	rows, err := q.db.QueryContext(ctx, listAllAgentNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentNote{}
	for rows.Next() {
		var i AgentNote
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAgentNotes = `-- name: PruneAgentNotes :execrows
DELETE FROM agent_notes
WHERE updated_at < ?1
`

func (q *Queries) PruneAgentNotes(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAgentNotes, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAgentNote = `-- name: UpsertAgentNote :one

INSERT INTO agent_notes (entity_type, entity_id, note, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(entity_type, entity_id) DO UPDATE SET note = excluded.note, updated_at = excluded.updated_at
RETURNING id, entity_type, entity_id, note, created_at, updated_at
`

type UpsertAgentNoteParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Note       string `json:"note"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

// Agent notes: persistent memory for the AI agent across sessions.
// Allows the agent to remember findings about queries, endpoints, services, etc.
func (q *Queries) UpsertAgentNote(ctx context.Context, arg UpsertAgentNoteParams) (AgentNote, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentNote,
		arg.EntityType,
		arg.EntityID,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AgentNote
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
