// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
)

const pruneEndpointStats = `-- name: PruneEndpointStats :execrows

DELETE FROM endpoint_stats WHERE period_start < ?1
`

// Analytics: endpoint stats and traffic heatmap.
// Only STATIC queries here; aggregation and dynamic queries use squirrel.
func (q *Queries) PruneEndpointStats(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEndpointStats, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneTrafficHeatmap = `-- name: PruneTrafficHeatmap :exec
DELETE FROM traffic_heatmap WHERE updated_at < ?1
`

func (q *Queries) PruneTrafficHeatmap(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, pruneTrafficHeatmap, cutoff)
	return err
}
