// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"database/sql"
)

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_log (user_id, user_email, action, target_type, target_id, details, ip_address)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertAuditLogParams struct {
	UserID     string         `json:"user_id"`
	UserEmail  string         `json:"user_email"`
	Action     string         `json:"action"`
	TargetType sql.NullString `json:"target_type"`
	TargetID   sql.NullString `json:"target_id"`
	Details    sql.NullString `json:"details"`
	IpAddress  sql.NullString `json:"ip_address"`
}

// Audit log: tracks user actions for security and compliance.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.UserEmail,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const listRecentAuditLogs = `-- name: ListRecentAuditLogs :many
SELECT id, user_id, user_email, action,
       COALESCE(target_type, '') AS target_type,
       COALESCE(target_id, '') AS target_id,
       COALESCE(details, '') AS details,
       COALESCE(ip_address, '') AS ip_address,
       created_at
FROM audit_log
ORDER BY created_at DESC
LIMIT ?1
`

type ListRecentAuditLogsRow struct {
	ID         int64  `json:"id"`
	UserID     string `json:"user_id"`
	UserEmail  string `json:"user_email"`
	Action     string `json:"action"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Details    string `json:"details"`
	IpAddress  string `json:"ip_address"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) ListRecentAuditLogs(ctx context.Context, maxResults int64) ([]ListRecentAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAuditLogs, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAuditLogsRow{}
	for rows.Next() {
		var i ListRecentAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditLogs = `-- name: PruneAuditLogs :execrows
DELETE FROM audit_log
WHERE rowid IN (
    SELECT a.rowid FROM audit_log a WHERE a.created_at < ?1 LIMIT 1000
)
`

func (q *Queries) PruneAuditLogs(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAuditLogs, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
