// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code_entities.sql

package db

import (
	"context"
	"database/sql"
)

const batchRecomputeCodeEntityRisk = `-- name: BatchRecomputeCodeEntityRisk :exec
UPDATE code_entities SET
  risk_score = (
    0.4 * MIN(error_count / 10.0, 1.0) +
    0.3 * MIN(investigation_count / 5.0, 1.0) +
    0.2 * CASE
      WHEN last_error_at IS NULL THEN 0.0
      WHEN (julianday(?1) - julianday(last_error_at)) < 1.0 THEN 1.0
      WHEN (julianday(?1) - julianday(last_error_at)) < 7.0 THEN
        1.0 - ((julianday(?1) - julianday(last_error_at)) / 7.0)
      ELSE 0.0
    END +
    0.1 * CASE
      WHEN last_investigation_at IS NULL THEN 0.0
      WHEN (julianday(?1) - julianday(last_investigation_at)) < 7.0 THEN 1.0
      ELSE 0.0
    END
  ),
  updated_at = ?1
WHERE error_count > 0 OR investigation_count > 0
`

func (q *Queries) BatchRecomputeCodeEntityRisk(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, batchRecomputeCodeEntityRisk, now)
	return err
}

const getCodeEntityByName = `-- name: GetCodeEntityByName :one
SELECT id, entity_type, entity_name, service, risk_score, error_count,
       investigation_count, avg_duration_ms, last_error_at, last_investigation_at,
       metadata_json, created_at, updated_at
FROM code_entities
WHERE entity_type = ?1 AND entity_name = ?2 AND service = ?3
`

type GetCodeEntityByNameParams struct {
	EntityType string `json:"entity_type"`
	EntityName string `json:"entity_name"`
	Service    string `json:"service"`
}

func (q *Queries) GetCodeEntityByName(ctx context.Context, arg GetCodeEntityByNameParams) (CodeEntity, error) {
	row := q.db.QueryRowContext(ctx, getCodeEntityByName, arg.EntityType, arg.EntityName, arg.Service)
	var i CodeEntity
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityName,
		&i.Service,
		&i.RiskScore,
		&i.ErrorCount,
		&i.InvestigationCount,
		&i.AvgDurationMs,
		&i.LastErrorAt,
		&i.LastInvestigationAt,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCodeEntityError = `-- name: IncrementCodeEntityError :exec
INSERT INTO code_entities (entity_type, entity_name, service, error_count, last_error_at, created_at, updated_at)
VALUES (?1, ?2, ?3, 1, ?4, ?4, ?4)
ON CONFLICT(entity_type, entity_name, service) DO UPDATE SET
  error_count = error_count + 1,
  last_error_at = sqlc.arg(now),
  updated_at = sqlc.arg(now)
`

type IncrementCodeEntityErrorParams struct {
	EntityType string         `json:"entity_type"`
	EntityName string         `json:"entity_name"`
	Service    string         `json:"service"`
	Now        sql.NullString `json:"now"`
}

func (q *Queries) IncrementCodeEntityError(ctx context.Context, arg IncrementCodeEntityErrorParams) error {
	_, err := q.db.ExecContext(ctx, incrementCodeEntityError,
		arg.EntityType,
		arg.EntityName,
		arg.Service,
		arg.Now,
	)
	return err
}

const incrementCodeEntityInvestigation = `-- name: IncrementCodeEntityInvestigation :exec
INSERT INTO code_entities (entity_type, entity_name, service, investigation_count, last_investigation_at, created_at, updated_at)
VALUES (?1, ?2, ?3, 1, ?4, ?4, ?4)
ON CONFLICT(entity_type, entity_name, service) DO UPDATE SET
  investigation_count = investigation_count + 1,
  last_investigation_at = sqlc.arg(now),
  updated_at = sqlc.arg(now)
`

type IncrementCodeEntityInvestigationParams struct {
	EntityType string         `json:"entity_type"`
	EntityName string         `json:"entity_name"`
	Service    string         `json:"service"`
	Now        sql.NullString `json:"now"`
}

func (q *Queries) IncrementCodeEntityInvestigation(ctx context.Context, arg IncrementCodeEntityInvestigationParams) error {
	_, err := q.db.ExecContext(ctx, incrementCodeEntityInvestigation,
		arg.EntityType,
		arg.EntityName,
		arg.Service,
		arg.Now,
	)
	return err
}

const listTopCodeEntitiesByRisk = `-- name: ListTopCodeEntitiesByRisk :many
SELECT id, entity_type, entity_name, service, risk_score, error_count,
       investigation_count, avg_duration_ms, last_error_at, last_investigation_at,
       metadata_json, created_at, updated_at
FROM code_entities
ORDER BY risk_score DESC
LIMIT ?1
`

func (q *Queries) ListTopCodeEntitiesByRisk(ctx context.Context, maxResults int64) ([]CodeEntity, error) {
	rows, err := q.db.QueryContext(ctx, listTopCodeEntitiesByRisk, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeEntity{}
	for rows.Next() {
		var i CodeEntity
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityName,
			&i.Service,
			&i.RiskScore,
			&i.ErrorCount,
			&i.InvestigationCount,
			&i.AvgDurationMs,
			&i.LastErrorAt,
			&i.LastInvestigationAt,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopCodeEntitiesByRiskForService = `-- name: ListTopCodeEntitiesByRiskForService :many
SELECT id, entity_type, entity_name, service, risk_score, error_count,
       investigation_count, avg_duration_ms, last_error_at, last_investigation_at,
       metadata_json, created_at, updated_at
FROM code_entities
WHERE service = ?1
ORDER BY risk_score DESC
LIMIT ?2
`

type ListTopCodeEntitiesByRiskForServiceParams struct {
	Service    string `json:"service"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) ListTopCodeEntitiesByRiskForService(ctx context.Context, arg ListTopCodeEntitiesByRiskForServiceParams) ([]CodeEntity, error) {
	rows, err := q.db.QueryContext(ctx, listTopCodeEntitiesByRiskForService, arg.Service, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeEntity{}
	for rows.Next() {
		var i CodeEntity
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityName,
			&i.Service,
			&i.RiskScore,
			&i.ErrorCount,
			&i.InvestigationCount,
			&i.AvgDurationMs,
			&i.LastErrorAt,
			&i.LastInvestigationAt,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCodeEntities = `-- name: PruneCodeEntities :execrows
DELETE FROM code_entities
WHERE error_count = 0 AND investigation_count = 0 AND updated_at < ?1
`

func (q *Queries) PruneCodeEntities(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneCodeEntities, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCodeEntity = `-- name: UpsertCodeEntity :exec

INSERT INTO code_entities (entity_type, entity_name, service, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?4)
ON CONFLICT(entity_type, entity_name, service) DO UPDATE SET updated_at = sqlc.arg(now)
`

type UpsertCodeEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityName string `json:"entity_name"`
	Service    string `json:"service"`
	Now        string `json:"now"`
}

// Code entities: file/controller/endpoint risk registry.
// Table: code_entities (migration 000042)
// NOTE: BatchGetRisk uses dynamic IN(...) clause -- skip here, will use squirrel.
func (q *Queries) UpsertCodeEntity(ctx context.Context, arg UpsertCodeEntityParams) error {
	_, err := q.db.ExecContext(ctx, upsertCodeEntity,
		arg.EntityType,
		arg.EntityName,
		arg.Service,
		arg.Now,
	)
	return err
}
