// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data_sources.sql

package db

import (
	"context"
	"database/sql"
)

const createDataSource = `-- name: CreateDataSource :exec

INSERT INTO data_sources (id, type, name, config, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateDataSourceParams struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Name      string `json:"name"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// Data sources: external database/log/monitoring connections managed by OpenTrace.
func (q *Queries) CreateDataSource(ctx context.Context, arg CreateDataSourceParams) error {
	_, err := q.db.ExecContext(ctx, createDataSource,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDataSource = `-- name: DeleteDataSource :execrows
DELETE FROM data_sources
WHERE id = ?1
`

func (q *Queries) DeleteDataSource(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDataSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDataSourceByID = `-- name: GetDataSourceByID :one
SELECT id, type, name, config, status, status_message, last_tested_at, created_at, updated_at
FROM data_sources
WHERE id = ?1
`

type GetDataSourceByIDRow struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Name          string         `json:"name"`
	Config        string         `json:"config"`
	Status        string         `json:"status"`
	StatusMessage sql.NullString `json:"status_message"`
	LastTestedAt  sql.NullString `json:"last_tested_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

func (q *Queries) GetDataSourceByID(ctx context.Context, id string) (GetDataSourceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDataSourceByID, id)
	var i GetDataSourceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Status,
		&i.StatusMessage,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDataSources = `-- name: ListAllDataSources :many
SELECT id, type, name, config, status, status_message, last_tested_at, created_at, updated_at
FROM data_sources
ORDER BY created_at DESC
`

type ListAllDataSourcesRow struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Name          string         `json:"name"`
	Config        string         `json:"config"`
	Status        string         `json:"status"`
	StatusMessage sql.NullString `json:"status_message"`
	LastTestedAt  sql.NullString `json:"last_tested_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

func (q *Queries) ListAllDataSources(ctx context.Context) ([]ListAllDataSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDataSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDataSourcesRow{}
	for rows.Next() {
		var i ListAllDataSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StatusMessage,
			&i.LastTestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataSourcesByType = `-- name: ListDataSourcesByType :many
SELECT id, type, name, config, status, status_message, last_tested_at, created_at, updated_at
FROM data_sources
WHERE type = ?1
ORDER BY created_at DESC
`

type ListDataSourcesByTypeRow struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Name          string         `json:"name"`
	Config        string         `json:"config"`
	Status        string         `json:"status"`
	StatusMessage sql.NullString `json:"status_message"`
	LastTestedAt  sql.NullString `json:"last_tested_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

func (q *Queries) ListDataSourcesByType(ctx context.Context, type_ string) ([]ListDataSourcesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listDataSourcesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDataSourcesByTypeRow{}
	for rows.Next() {
		var i ListDataSourcesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Status,
			&i.StatusMessage,
			&i.LastTestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
