// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deploys.sql

package db

import (
	"context"
	"database/sql"
)

const createDeploy = `-- name: CreateDeploy :one

INSERT INTO deploys (service, environment, commit_hash, branch, author,
                     files_changed_json, deploy_source, deployed_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8, ?9)
RETURNING id, service, environment, commit_hash, branch, author, files_changed_json, deploy_source, pre_error_rate, post_error_rate, pre_avg_duration_ms, post_avg_duration_ms, impact_measured_at, linked_investigation_ids_json, status, deployed_at, created_at
`

type CreateDeployParams struct {
	Service          string `json:"service"`
	Environment      string `json:"environment"`
	CommitHash       string `json:"commit_hash"`
	Branch           string `json:"branch"`
	Author           string `json:"author"`
	FilesChangedJson string `json:"files_changed_json"`
	DeploySource     string `json:"deploy_source"`
	DeployedAt       string `json:"deployed_at"`
	CreatedAt        string `json:"created_at"`
}

// Deploys: deploy tracking and impact measurement.
// Table: deploys (migration 000042)
func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, createDeploy,
		arg.Service,
		arg.Environment,
		arg.CommitHash,
		arg.Branch,
		arg.Author,
		arg.FilesChangedJson,
		arg.DeploySource,
		arg.DeployedAt,
		arg.CreatedAt,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Environment,
		&i.CommitHash,
		&i.Branch,
		&i.Author,
		&i.FilesChangedJson,
		&i.DeploySource,
		&i.PreErrorRate,
		&i.PostErrorRate,
		&i.PreAvgDurationMs,
		&i.PostAvgDurationMs,
		&i.ImpactMeasuredAt,
		&i.LinkedInvestigationIdsJson,
		&i.Status,
		&i.DeployedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployByCommit = `-- name: GetDeployByCommit :one
SELECT id, service, environment, commit_hash, branch, author,
       files_changed_json, deploy_source,
       pre_error_rate, post_error_rate, pre_avg_duration_ms, post_avg_duration_ms,
       impact_measured_at, linked_investigation_ids_json, status,
       deployed_at, created_at
FROM deploys WHERE commit_hash = ?1
ORDER BY deployed_at DESC LIMIT 1
`

func (q *Queries) GetDeployByCommit(ctx context.Context, commitHash string) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, getDeployByCommit, commitHash)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Environment,
		&i.CommitHash,
		&i.Branch,
		&i.Author,
		&i.FilesChangedJson,
		&i.DeploySource,
		&i.PreErrorRate,
		&i.PostErrorRate,
		&i.PreAvgDurationMs,
		&i.PostAvgDurationMs,
		&i.ImpactMeasuredAt,
		&i.LinkedInvestigationIdsJson,
		&i.Status,
		&i.DeployedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployByID = `-- name: GetDeployByID :one
SELECT id, service, environment, commit_hash, branch, author,
       files_changed_json, deploy_source,
       pre_error_rate, post_error_rate, pre_avg_duration_ms, post_avg_duration_ms,
       impact_measured_at, linked_investigation_ids_json, status,
       deployed_at, created_at
FROM deploys WHERE id = ?1
`

func (q *Queries) GetDeployByID(ctx context.Context, id int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, getDeployByID, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Environment,
		&i.CommitHash,
		&i.Branch,
		&i.Author,
		&i.FilesChangedJson,
		&i.DeploySource,
		&i.PreErrorRate,
		&i.PostErrorRate,
		&i.PreAvgDurationMs,
		&i.PostAvgDurationMs,
		&i.ImpactMeasuredAt,
		&i.LinkedInvestigationIdsJson,
		&i.Status,
		&i.DeployedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployLinkedInvestigations = `-- name: GetDeployLinkedInvestigations :one
SELECT linked_investigation_ids_json FROM deploys WHERE id = ?1
`

func (q *Queries) GetDeployLinkedInvestigations(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getDeployLinkedInvestigations, id)
	var linked_investigation_ids_json string
	err := row.Scan(&linked_investigation_ids_json)
	return linked_investigation_ids_json, err
}

const listPendingMeasurement = `-- name: ListPendingMeasurement :many
SELECT id, service, environment, commit_hash, branch, author,
       files_changed_json, deploy_source,
       pre_error_rate, post_error_rate, pre_avg_duration_ms, post_avg_duration_ms,
       impact_measured_at, linked_investigation_ids_json, status,
       deployed_at, created_at
FROM deploys
WHERE status = 'pending' AND deployed_at < ?1
ORDER BY deployed_at ASC
`

func (q *Queries) ListPendingMeasurement(ctx context.Context, cutoff string) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMeasurement, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deploy{}
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Environment,
			&i.CommitHash,
			&i.Branch,
			&i.Author,
			&i.FilesChangedJson,
			&i.DeploySource,
			&i.PreErrorRate,
			&i.PostErrorRate,
			&i.PreAvgDurationMs,
			&i.PostAvgDurationMs,
			&i.ImpactMeasuredAt,
			&i.LinkedInvestigationIdsJson,
			&i.Status,
			&i.DeployedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeploys = `-- name: ListRecentDeploys :many
SELECT id, service, environment, commit_hash, branch, author,
       files_changed_json, deploy_source,
       pre_error_rate, post_error_rate, pre_avg_duration_ms, post_avg_duration_ms,
       impact_measured_at, linked_investigation_ids_json, status,
       deployed_at, created_at
FROM deploys
ORDER BY deployed_at DESC LIMIT ?1
`

func (q *Queries) ListRecentDeploys(ctx context.Context, maxResults int64) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeploys, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deploy{}
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Environment,
			&i.CommitHash,
			&i.Branch,
			&i.Author,
			&i.FilesChangedJson,
			&i.DeploySource,
			&i.PreErrorRate,
			&i.PostErrorRate,
			&i.PreAvgDurationMs,
			&i.PostAvgDurationMs,
			&i.ImpactMeasuredAt,
			&i.LinkedInvestigationIdsJson,
			&i.Status,
			&i.DeployedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeploysByService = `-- name: ListRecentDeploysByService :many
SELECT id, service, environment, commit_hash, branch, author,
       files_changed_json, deploy_source,
       pre_error_rate, post_error_rate, pre_avg_duration_ms, post_avg_duration_ms,
       impact_measured_at, linked_investigation_ids_json, status,
       deployed_at, created_at
FROM deploys WHERE service = ?1
ORDER BY deployed_at DESC LIMIT ?2
`

type ListRecentDeploysByServiceParams struct {
	Service    string `json:"service"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) ListRecentDeploysByService(ctx context.Context, arg ListRecentDeploysByServiceParams) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeploysByService, arg.Service, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deploy{}
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Environment,
			&i.CommitHash,
			&i.Branch,
			&i.Author,
			&i.FilesChangedJson,
			&i.DeploySource,
			&i.PreErrorRate,
			&i.PostErrorRate,
			&i.PreAvgDurationMs,
			&i.PostAvgDurationMs,
			&i.ImpactMeasuredAt,
			&i.LinkedInvestigationIdsJson,
			&i.Status,
			&i.DeployedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const measureDeployImpact = `-- name: MeasureDeployImpact :exec
UPDATE deploys SET
  pre_error_rate = ?1,
  post_error_rate = ?2,
  pre_avg_duration_ms = ?3,
  post_avg_duration_ms = ?4,
  impact_measured_at = ?5,
  status = ?6
WHERE id = ?7
`

type MeasureDeployImpactParams struct {
	PreErrorRate      sql.NullFloat64 `json:"pre_error_rate"`
	PostErrorRate     sql.NullFloat64 `json:"post_error_rate"`
	PreAvgDurationMs  sql.NullFloat64 `json:"pre_avg_duration_ms"`
	PostAvgDurationMs sql.NullFloat64 `json:"post_avg_duration_ms"`
	ImpactMeasuredAt  sql.NullString  `json:"impact_measured_at"`
	Status            string          `json:"status"`
	ID                int64           `json:"id"`
}

func (q *Queries) MeasureDeployImpact(ctx context.Context, arg MeasureDeployImpactParams) error {
	_, err := q.db.ExecContext(ctx, measureDeployImpact,
		arg.PreErrorRate,
		arg.PostErrorRate,
		arg.PreAvgDurationMs,
		arg.PostAvgDurationMs,
		arg.ImpactMeasuredAt,
		arg.Status,
		arg.ID,
	)
	return err
}

const pruneDeploys = `-- name: PruneDeploys :execrows
DELETE FROM deploys WHERE deployed_at < ?1
`

func (q *Queries) PruneDeploys(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneDeploys, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeployLinkedInvestigations = `-- name: UpdateDeployLinkedInvestigations :exec
UPDATE deploys SET linked_investigation_ids_json = ?1
WHERE id = ?2
`

type UpdateDeployLinkedInvestigationsParams struct {
	LinkedInvestigationIdsJson string `json:"linked_investigation_ids_json"`
	ID                         int64  `json:"id"`
}

func (q *Queries) UpdateDeployLinkedInvestigations(ctx context.Context, arg UpdateDeployLinkedInvestigationsParams) error {
	_, err := q.db.ExecContext(ctx, updateDeployLinkedInvestigations, arg.LinkedInvestigationIdsJson, arg.ID)
	return err
}
