// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: error_groups.sql

package db

import (
	"context"
	"database/sql"
)

const countAllErrorGroups = `-- name: CountAllErrorGroups :one

SELECT COUNT(*) FROM error_groups
`

// DYNAMIC: use squirrel for ListErrorGroups with optional status/service/environment/sort filters
func (q *Queries) CountAllErrorGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllErrorGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countErrorGroupsByStatus = `-- name: CountErrorGroupsByStatus :one
SELECT COUNT(*) FROM error_groups WHERE status = ?1
`

func (q *Queries) CountErrorGroupsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countErrorGroupsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getErrorGroup = `-- name: GetErrorGroup :one
SELECT fingerprint, service, environment, exception_class, message,
       source_file, source_line, status, first_seen_at, last_seen_at,
       occurrence_count, last_log_id, reopened_count, resolved_at, ignored_at,
       unique_users, impact_score, COALESCE(common_context, '{}') AS common_context
FROM error_groups WHERE fingerprint = ?1
`

func (q *Queries) GetErrorGroup(ctx context.Context, fingerprint string) (ErrorGroup, error) {
	row := q.db.QueryRowContext(ctx, getErrorGroup, fingerprint)
	var i ErrorGroup
	err := row.Scan(
		&i.Fingerprint,
		&i.Service,
		&i.Environment,
		&i.ExceptionClass,
		&i.Message,
		&i.SourceFile,
		&i.SourceLine,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.OccurrenceCount,
		&i.LastLogID,
		&i.ReopenedCount,
		&i.ResolvedAt,
		&i.IgnoredAt,
		&i.UniqueUsers,
		&i.ImpactScore,
		&i.CommonContext,
	)
	return i, err
}

const getErrorGroupStatus = `-- name: GetErrorGroupStatus :one
SELECT status FROM error_groups WHERE fingerprint = ?1
`

func (q *Queries) GetErrorGroupStatus(ctx context.Context, fingerprint string) (string, error) {
	row := q.db.QueryRowContext(ctx, getErrorGroupStatus, fingerprint)
	var status string
	err := row.Scan(&status)
	return status, err
}

const ignoreErrorGroup = `-- name: IgnoreErrorGroup :execrows
UPDATE error_groups SET status = 'ignored', ignored_at = ?1
WHERE fingerprint = ?2
`

type IgnoreErrorGroupParams struct {
	IgnoredAt   sql.NullString `json:"ignored_at"`
	Fingerprint string         `json:"fingerprint"`
}

func (q *Queries) IgnoreErrorGroup(ctx context.Context, arg IgnoreErrorGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ignoreErrorGroup, arg.IgnoredAt, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incrementErrorGroupCount = `-- name: IncrementErrorGroupCount :exec
UPDATE error_groups
SET occurrence_count = occurrence_count + 1,
    last_seen_at = ?1,
    last_log_id = ?2
WHERE fingerprint = ?3
`

type IncrementErrorGroupCountParams struct {
	LastSeenAt  string        `json:"last_seen_at"`
	LastLogID   sql.NullInt64 `json:"last_log_id"`
	Fingerprint string        `json:"fingerprint"`
}

func (q *Queries) IncrementErrorGroupCount(ctx context.Context, arg IncrementErrorGroupCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementErrorGroupCount, arg.LastSeenAt, arg.LastLogID, arg.Fingerprint)
	return err
}

const insertErrorGroup = `-- name: InsertErrorGroup :exec

INSERT INTO error_groups (fingerprint, service, environment, exception_class,
    message, source_file, source_line, status, first_seen_at, last_seen_at,
    occurrence_count, last_log_id)
VALUES (?1, ?2, ?3, ?4,
    ?5, ?6, ?7, 'unresolved',
    ?8, ?9, 1, ?10)
`

type InsertErrorGroupParams struct {
	Fingerprint    string        `json:"fingerprint"`
	Service        string        `json:"service"`
	Environment    string        `json:"environment"`
	ExceptionClass string        `json:"exception_class"`
	Message        string        `json:"message"`
	SourceFile     string        `json:"source_file"`
	SourceLine     int64         `json:"source_line"`
	FirstSeenAt    string        `json:"first_seen_at"`
	LastSeenAt     string        `json:"last_seen_at"`
	LastLogID      sql.NullInt64 `json:"last_log_id"`
}

// Error groups: aggregate errors by fingerprint (Sentry-lite).
// Queries for error_groups and error_group_events tables.
func (q *Queries) InsertErrorGroup(ctx context.Context, arg InsertErrorGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertErrorGroup,
		arg.Fingerprint,
		arg.Service,
		arg.Environment,
		arg.ExceptionClass,
		arg.Message,
		arg.SourceFile,
		arg.SourceLine,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.LastLogID,
	)
	return err
}

const insertErrorGroupEvent = `-- name: InsertErrorGroupEvent :exec
INSERT INTO error_group_events (fingerprint, action, reason, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type InsertErrorGroupEventParams struct {
	Fingerprint string `json:"fingerprint"`
	Action      string `json:"action"`
	Reason      string `json:"reason"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertErrorGroupEvent(ctx context.Context, arg InsertErrorGroupEventParams) error {
	_, err := q.db.ExecContext(ctx, insertErrorGroupEvent,
		arg.Fingerprint,
		arg.Action,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const listErrorGroupEvents = `-- name: ListErrorGroupEvents :many
SELECT id, fingerprint, action, reason, created_at
FROM error_group_events
WHERE fingerprint = ?1
ORDER BY created_at DESC
LIMIT ?2
`

type ListErrorGroupEventsParams struct {
	Fingerprint string `json:"fingerprint"`
	RowLimit    int64  `json:"row_limit"`
}

func (q *Queries) ListErrorGroupEvents(ctx context.Context, arg ListErrorGroupEventsParams) ([]ErrorGroupEvent, error) {
	rows, err := q.db.QueryContext(ctx, listErrorGroupEvents, arg.Fingerprint, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorGroupEvent{}
	for rows.Next() {
		var i ErrorGroupEvent
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Action,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneErrorGroups = `-- name: PruneErrorGroups :execrows
DELETE FROM error_groups WHERE last_seen_at < ?1
`

func (q *Queries) PruneErrorGroups(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneErrorGroups, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reopenErrorGroup = `-- name: ReopenErrorGroup :exec
UPDATE error_groups
SET status = 'unresolved',
    reopened_count = reopened_count + 1,
    resolved_at = NULL
WHERE fingerprint = ?1
`

func (q *Queries) ReopenErrorGroup(ctx context.Context, fingerprint string) error {
	_, err := q.db.ExecContext(ctx, reopenErrorGroup, fingerprint)
	return err
}

const resolveErrorGroup = `-- name: ResolveErrorGroup :execrows
UPDATE error_groups SET status = 'resolved', resolved_at = ?1
WHERE fingerprint = ?2
`

type ResolveErrorGroupParams struct {
	ResolvedAt  sql.NullString `json:"resolved_at"`
	Fingerprint string         `json:"fingerprint"`
}

func (q *Queries) ResolveErrorGroup(ctx context.Context, arg ResolveErrorGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveErrorGroup, arg.ResolvedAt, arg.Fingerprint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
