// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: error_impact.sql

package db

import (
	"context"
	"database/sql"
)

const aggregateImpactData = `-- name: AggregateImpactData :many
SELECT error_fingerprint,
       COUNT(DISTINCT user_id) AS unique_users,
       SUM(occurrence_count) AS total_occurrences,
       MAX(last_seen_at) AS last_seen
FROM error_impacts
GROUP BY error_fingerprint
`

type AggregateImpactDataRow struct {
	ErrorFingerprint string          `json:"error_fingerprint"`
	UniqueUsers      int64           `json:"unique_users"`
	TotalOccurrences sql.NullFloat64 `json:"total_occurrences"`
	LastSeen         interface{}     `json:"last_seen"`
}

func (q *Queries) AggregateImpactData(ctx context.Context) ([]AggregateImpactDataRow, error) {
	rows, err := q.db.QueryContext(ctx, aggregateImpactData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateImpactDataRow{}
	for rows.Next() {
		var i AggregateImpactDataRow
		if err := rows.Scan(
			&i.ErrorFingerprint,
			&i.UniqueUsers,
			&i.TotalOccurrences,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getErrorImpact = `-- name: GetErrorImpact :one
SELECT COUNT(DISTINCT user_id) AS unique_users,
       SUM(occurrence_count) AS total_occurrences
FROM error_impacts
WHERE error_fingerprint = ?1
`

type GetErrorImpactRow struct {
	UniqueUsers      int64           `json:"unique_users"`
	TotalOccurrences sql.NullFloat64 `json:"total_occurrences"`
}

func (q *Queries) GetErrorImpact(ctx context.Context, fingerprint string) (GetErrorImpactRow, error) {
	row := q.db.QueryRowContext(ctx, getErrorImpact, fingerprint)
	var i GetErrorImpactRow
	err := row.Scan(&i.UniqueUsers, &i.TotalOccurrences)
	return i, err
}

const getErrorImpactScore = `-- name: GetErrorImpactScore :one
SELECT COALESCE(impact_score, 0) AS impact_score
FROM error_groups WHERE fingerprint = ?1
`

func (q *Queries) GetErrorImpactScore(ctx context.Context, fingerprint string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getErrorImpactScore, fingerprint)
	var impact_score float64
	err := row.Scan(&impact_score)
	return impact_score, err
}

const listAffectedUsers = `-- name: ListAffectedUsers :many
SELECT user_id, occurrence_count, first_seen_at, last_seen_at, last_context
FROM error_impacts
WHERE error_fingerprint = ?1
ORDER BY occurrence_count DESC
LIMIT ?2
`

type ListAffectedUsersParams struct {
	Fingerprint string `json:"fingerprint"`
	RowLimit    int64  `json:"row_limit"`
}

type ListAffectedUsersRow struct {
	UserID          string `json:"user_id"`
	OccurrenceCount int64  `json:"occurrence_count"`
	FirstSeenAt     string `json:"first_seen_at"`
	LastSeenAt      string `json:"last_seen_at"`
	LastContext     string `json:"last_context"`
}

func (q *Queries) ListAffectedUsers(ctx context.Context, arg ListAffectedUsersParams) ([]ListAffectedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAffectedUsers, arg.Fingerprint, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAffectedUsersRow{}
	for rows.Next() {
		var i ListAffectedUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.OccurrenceCount,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneErrorImpacts = `-- name: PruneErrorImpacts :execrows

DELETE FROM error_impacts WHERE last_seen_at < ?1
`

// DYNAMIC: use squirrel for GetUserErrors (joins error_impacts + error_groups with user_id + since filters)
// DYNAMIC: use squirrel for TopByImpact (dynamic status/service/since/sort filters)
// DYNAMIC: use squirrel for FindCommonTraits (application-level aggregation of JSON contexts)
func (q *Queries) PruneErrorImpacts(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneErrorImpacts, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const trackErrorImpact = `-- name: TrackErrorImpact :exec

INSERT INTO error_impacts (error_fingerprint, user_id, service, first_seen_at, last_seen_at, occurrence_count, last_context, last_log_id)
VALUES (?1, ?2, ?3, ?4, ?5, 1, ?6, ?7)
ON CONFLICT(error_fingerprint, user_id) DO UPDATE SET
    last_seen_at = excluded.last_seen_at,
    occurrence_count = error_impacts.occurrence_count + 1,
    last_context = excluded.last_context,
    last_log_id = excluded.last_log_id
`

type TrackErrorImpactParams struct {
	ErrorFingerprint string `json:"error_fingerprint"`
	UserID           string `json:"user_id"`
	Service          string `json:"service"`
	FirstSeenAt      string `json:"first_seen_at"`
	LastSeenAt       string `json:"last_seen_at"`
	LastContext      string `json:"last_context"`
	LastLogID        int64  `json:"last_log_id"`
}

// Error impact: cohort-based error impact tracking.
// Queries for error_impacts table and impact-related error_groups updates.
func (q *Queries) TrackErrorImpact(ctx context.Context, arg TrackErrorImpactParams) error {
	_, err := q.db.ExecContext(ctx, trackErrorImpact,
		arg.ErrorFingerprint,
		arg.UserID,
		arg.Service,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.LastContext,
		arg.LastLogID,
	)
	return err
}

const updateErrorGroupImpact = `-- name: UpdateErrorGroupImpact :exec
UPDATE error_groups
SET unique_users = ?1, impact_score = ?2, common_context = ?3
WHERE fingerprint = ?4
`

type UpdateErrorGroupImpactParams struct {
	UniqueUsers   int64   `json:"unique_users"`
	ImpactScore   float64 `json:"impact_score"`
	CommonContext string  `json:"common_context"`
	Fingerprint   string  `json:"fingerprint"`
}

func (q *Queries) UpdateErrorGroupImpact(ctx context.Context, arg UpdateErrorGroupImpactParams) error {
	_, err := q.db.ExecContext(ctx, updateErrorGroupImpact,
		arg.UniqueUsers,
		arg.ImpactScore,
		arg.CommonContext,
		arg.Fingerprint,
	)
	return err
}
