// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (event_type, source, service, title, description,
                    metadata_json, external_id, external_url, author, created_at)
VALUES (?1, ?2, ?3,
        ?4, ?5, ?6,
        ?7, ?8, ?9,
        ?10)
RETURNING id, event_type, source, service, title, description, metadata_json, external_id, external_url, author, created_at
`

type CreateEventParams struct {
	EventType    string `json:"event_type"`
	Source       string `json:"source"`
	Service      string `json:"service"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	MetadataJson string `json:"metadata_json"`
	ExternalID   string `json:"external_id"`
	ExternalUrl  string `json:"external_url"`
	Author       string `json:"author"`
	CreatedAt    string `json:"created_at"`
}

// Events: generic CI/CD integration events.
// Table: events (migration 000043)
// NOTE: ListEvents uses dynamic WHERE clauses -- skip here, will use squirrel.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.EventType,
		arg.Source,
		arg.Service,
		arg.Title,
		arg.Description,
		arg.MetadataJson,
		arg.ExternalID,
		arg.ExternalUrl,
		arg.Author,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Source,
		&i.Service,
		&i.Title,
		&i.Description,
		&i.MetadataJson,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByExternalID = `-- name: GetEventByExternalID :one
SELECT id, event_type, source, service, title, description,
       metadata_json, external_id, external_url, author, created_at
FROM events WHERE event_type = ?1 AND external_id = ?2
`

type GetEventByExternalIDParams struct {
	EventType  string `json:"event_type"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetEventByExternalID(ctx context.Context, arg GetEventByExternalIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByExternalID, arg.EventType, arg.ExternalID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Source,
		&i.Service,
		&i.Title,
		&i.Description,
		&i.MetadataJson,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, event_type, source, service, title, description,
       metadata_json, external_id, external_url, author, created_at
FROM events WHERE id = ?1
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Source,
		&i.Service,
		&i.Title,
		&i.Description,
		&i.MetadataJson,
		&i.ExternalID,
		&i.ExternalUrl,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM events WHERE rowid IN (
  SELECT e.rowid FROM events e WHERE e.created_at < ?1 LIMIT 1000
)
`

func (q *Queries) PruneEvents(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEvents, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
