// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: healthchecks.sql

package db

import (
	"context"
	"database/sql"
)

const createHealthcheck = `-- name: CreateHealthcheck :exec

INSERT INTO healthchecks (id, name, url, method, interval_secs, timeout_secs, expected_status, expected_body, retries, enabled, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, 1, ?10)
`

type CreateHealthcheckParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Url            string `json:"url"`
	Method         string `json:"method"`
	IntervalSecs   int64  `json:"interval_secs"`
	TimeoutSecs    int64  `json:"timeout_secs"`
	ExpectedStatus int64  `json:"expected_status"`
	ExpectedBody   string `json:"expected_body"`
	Retries        int64  `json:"retries"`
	CreatedAt      string `json:"created_at"`
}

// Health checks: HTTP endpoint monitoring (UptimeRobot-lite).
// Queries for healthchecks and healthcheck_results tables.
func (q *Queries) CreateHealthcheck(ctx context.Context, arg CreateHealthcheckParams) error {
	_, err := q.db.ExecContext(ctx, createHealthcheck,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.IntervalSecs,
		arg.TimeoutSecs,
		arg.ExpectedStatus,
		arg.ExpectedBody,
		arg.Retries,
		arg.CreatedAt,
	)
	return err
}

const deleteHealthcheck = `-- name: DeleteHealthcheck :execrows
DELETE FROM healthchecks WHERE id = ?1
`

func (q *Queries) DeleteHealthcheck(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHealthcheck, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getHealthcheck = `-- name: GetHealthcheck :one
SELECT id, name, url, method, interval_secs, timeout_secs, expected_status, expected_body, retries, enabled, created_at
FROM healthchecks WHERE id = ?1
`

type GetHealthcheckRow struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Url            string `json:"url"`
	Method         string `json:"method"`
	IntervalSecs   int64  `json:"interval_secs"`
	TimeoutSecs    int64  `json:"timeout_secs"`
	ExpectedStatus int64  `json:"expected_status"`
	ExpectedBody   string `json:"expected_body"`
	Retries        int64  `json:"retries"`
	Enabled        int64  `json:"enabled"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) GetHealthcheck(ctx context.Context, id string) (GetHealthcheckRow, error) {
	row := q.db.QueryRowContext(ctx, getHealthcheck, id)
	var i GetHealthcheckRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.IntervalSecs,
		&i.TimeoutSecs,
		&i.ExpectedStatus,
		&i.ExpectedBody,
		&i.Retries,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertHealthcheckResult = `-- name: InsertHealthcheckResult :exec
INSERT INTO healthcheck_results (healthcheck_id, status, status_code, response_ms, error, checked_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertHealthcheckResultParams struct {
	HealthcheckID string        `json:"healthcheck_id"`
	Status        string        `json:"status"`
	StatusCode    sql.NullInt64 `json:"status_code"`
	ResponseMs    sql.NullInt64 `json:"response_ms"`
	Error         string        `json:"error"`
	CheckedAt     string        `json:"checked_at"`
}

func (q *Queries) InsertHealthcheckResult(ctx context.Context, arg InsertHealthcheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertHealthcheckResult,
		arg.HealthcheckID,
		arg.Status,
		arg.StatusCode,
		arg.ResponseMs,
		arg.Error,
		arg.CheckedAt,
	)
	return err
}

const listHealthchecks = `-- name: ListHealthchecks :many
SELECT id, name, url, method, interval_secs, timeout_secs, expected_status, expected_body, retries, enabled, created_at
FROM healthchecks ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListHealthchecksParams struct {
	RowOffset int64 `json:"row_offset"`
	RowLimit  int64 `json:"row_limit"`
}

type ListHealthchecksRow struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Url            string `json:"url"`
	Method         string `json:"method"`
	IntervalSecs   int64  `json:"interval_secs"`
	TimeoutSecs    int64  `json:"timeout_secs"`
	ExpectedStatus int64  `json:"expected_status"`
	ExpectedBody   string `json:"expected_body"`
	Retries        int64  `json:"retries"`
	Enabled        int64  `json:"enabled"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) ListHealthchecks(ctx context.Context, arg ListHealthchecksParams) ([]ListHealthchecksRow, error) {
	rows, err := q.db.QueryContext(ctx, listHealthchecks, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHealthchecksRow{}
	for rows.Next() {
		var i ListHealthchecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.IntervalSecs,
			&i.TimeoutSecs,
			&i.ExpectedStatus,
			&i.ExpectedBody,
			&i.Retries,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestHealthcheckResults = `-- name: ListLatestHealthcheckResults :many
SELECT id, healthcheck_id, status, status_code, response_ms, error, checked_at
FROM healthcheck_results
WHERE healthcheck_id = ?1
ORDER BY checked_at DESC
LIMIT ?2
`

type ListLatestHealthcheckResultsParams struct {
	HealthcheckID string `json:"healthcheck_id"`
	RowLimit      int64  `json:"row_limit"`
}

func (q *Queries) ListLatestHealthcheckResults(ctx context.Context, arg ListLatestHealthcheckResultsParams) ([]HealthcheckResult, error) {
	rows, err := q.db.QueryContext(ctx, listLatestHealthcheckResults, arg.HealthcheckID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthcheckResult{}
	for rows.Next() {
		var i HealthcheckResult
		if err := rows.Scan(
			&i.ID,
			&i.HealthcheckID,
			&i.Status,
			&i.StatusCode,
			&i.ResponseMs,
			&i.Error,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHealthcheckResults = `-- name: PruneHealthcheckResults :execrows
DELETE FROM healthcheck_results WHERE checked_at < ?1
`

func (q *Queries) PruneHealthcheckResults(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneHealthcheckResults, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setHealthcheckEnabled = `-- name: SetHealthcheckEnabled :execrows
UPDATE healthchecks SET enabled = ?1 WHERE id = ?2
`

type SetHealthcheckEnabledParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) SetHealthcheckEnabled(ctx context.Context, arg SetHealthcheckEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setHealthcheckEnabled, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uptimeSummaries = `-- name: UptimeSummaries :many
SELECT
    h.id,
    h.name,
    h.url,
    COALESCE((SELECT status FROM healthcheck_results WHERE healthcheck_id = h.id ORDER BY checked_at DESC LIMIT 1), 'unknown') AS current_status,
    COUNT(r.id) AS total_checks,
    SUM(CASE WHEN r.status = 'down' THEN 1 ELSE 0 END) AS down_checks,
    COALESCE(AVG(r.response_ms), 0) AS avg_response_ms
FROM healthchecks h
LEFT JOIN healthcheck_results r ON r.healthcheck_id = h.id AND r.checked_at >= ?1
GROUP BY h.id
ORDER BY h.name
`

type UptimeSummariesRow struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Url           string          `json:"url"`
	CurrentStatus interface{}     `json:"current_status"`
	TotalChecks   int64           `json:"total_checks"`
	DownChecks    sql.NullFloat64 `json:"down_checks"`
	AvgResponseMs interface{}     `json:"avg_response_ms"`
}

func (q *Queries) UptimeSummaries(ctx context.Context, since string) ([]UptimeSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, uptimeSummaries, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeSummariesRow{}
	for rows.Next() {
		var i UptimeSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.CurrentStatus,
			&i.TotalChecks,
			&i.DownChecks,
			&i.AvgResponseMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
