// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investigation_sessions.sql

package db

import (
	"context"
	"database/sql"
)

const closeInvestigationSession = `-- name: CloseInvestigationSession :exec
UPDATE investigation_sessions
SET ended_at = ?1, duration_seconds = ?2,
    last_activity_at = ?3,
    status = CASE WHEN status = 'open' THEN 'unresolved' ELSE status END
WHERE id = ?4
`

type CloseInvestigationSessionParams struct {
	EndedAt         sql.NullString `json:"ended_at"`
	DurationSeconds int64          `json:"duration_seconds"`
	LastActivityAt  string         `json:"last_activity_at"`
	ID              string         `json:"id"`
}

func (q *Queries) CloseInvestigationSession(ctx context.Context, arg CloseInvestigationSessionParams) error {
	_, err := q.db.ExecContext(ctx, closeInvestigationSession,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.LastActivityAt,
		arg.ID,
	)
	return err
}

const createInvestigationSession = `-- name: CreateInvestigationSession :exec

INSERT INTO investigation_sessions
    (id, user_id, user_email, user_role, client_name, client_version,
     workspace, transport, connection_id, status, started_at, last_activity_at)
VALUES (?1, ?2, ?3, ?4,
    ?5, ?6,
    ?7, ?8, ?9, 'open',
    ?10, ?11)
`

type CreateInvestigationSessionParams struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	UserEmail      string `json:"user_email"`
	UserRole       string `json:"user_role"`
	ClientName     string `json:"client_name"`
	ClientVersion  string `json:"client_version"`
	Workspace      string `json:"workspace"`
	Transport      string `json:"transport"`
	ConnectionID   string `json:"connection_id"`
	StartedAt      string `json:"started_at"`
	LastActivityAt string `json:"last_activity_at"`
}

// Investigation sessions: tracks MCP investigation lifecycle with full identity chain.
// Only STATIC queries here; dynamic Update/List/FindRecent/FindSimilar/FindBy* use squirrel.
func (q *Queries) CreateInvestigationSession(ctx context.Context, arg CreateInvestigationSessionParams) error {
	_, err := q.db.ExecContext(ctx, createInvestigationSession,
		arg.ID,
		arg.UserID,
		arg.UserEmail,
		arg.UserRole,
		arg.ClientName,
		arg.ClientVersion,
		arg.Workspace,
		arg.Transport,
		arg.ConnectionID,
		arg.StartedAt,
		arg.LastActivityAt,
	)
	return err
}

const getInvestigationSession = `-- name: GetInvestigationSession :one
SELECT id, user_id, user_email, user_role,
    client_name, client_version, workspace, transport, connection_id,
    intent, intent_detail, primary_service, primary_datasource_id,
    status, summary, root_cause, fix_description,
    created_watcher_ids, triggered_by_alert_id, triggered_by_watcher_id,
    resolved_error_group_ids, investigated_error_fingerprints,
    created_healthcheck_ids, triggered_by_healthcheck_id,
    created_note_ids, auto_note_ids,
    runbooks_executed, explained_queries, killed_queries, trace_ids,
    correlated_deploy, pre_investigation_snapshot, post_investigation_snapshot,
    total_steps, total_errors, tool_sequence, tool_fingerprint, arg_signature,
    started_at, last_activity_at, ended_at, duration_seconds,
    recurrence_group, recurrence_count, previous_session_id, fix_durability_seconds,
    files_modified, files_read, linked_deploy_id
FROM investigation_sessions
WHERE id = ?1
`

func (q *Queries) GetInvestigationSession(ctx context.Context, id string) (InvestigationSession, error) {
	row := q.db.QueryRowContext(ctx, getInvestigationSession, id)
	var i InvestigationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.UserRole,
		&i.ClientName,
		&i.ClientVersion,
		&i.Workspace,
		&i.Transport,
		&i.ConnectionID,
		&i.Intent,
		&i.IntentDetail,
		&i.PrimaryService,
		&i.PrimaryDatasourceID,
		&i.Status,
		&i.Summary,
		&i.RootCause,
		&i.FixDescription,
		&i.CreatedWatcherIds,
		&i.TriggeredByAlertID,
		&i.TriggeredByWatcherID,
		&i.ResolvedErrorGroupIds,
		&i.InvestigatedErrorFingerprints,
		&i.CreatedHealthcheckIds,
		&i.TriggeredByHealthcheckID,
		&i.CreatedNoteIds,
		&i.AutoNoteIds,
		&i.RunbooksExecuted,
		&i.ExplainedQueries,
		&i.KilledQueries,
		&i.TraceIds,
		&i.CorrelatedDeploy,
		&i.PreInvestigationSnapshot,
		&i.PostInvestigationSnapshot,
		&i.TotalSteps,
		&i.TotalErrors,
		&i.ToolSequence,
		&i.ToolFingerprint,
		&i.ArgSignature,
		&i.StartedAt,
		&i.LastActivityAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.RecurrenceGroup,
		&i.RecurrenceCount,
		&i.PreviousSessionID,
		&i.FixDurabilitySeconds,
		&i.FilesModified,
		&i.FilesRead,
		&i.LinkedDeployID,
	)
	return i, err
}

const getInvestigationSessionStartedAt = `-- name: GetInvestigationSessionStartedAt :one
SELECT started_at FROM investigation_sessions WHERE id = ?1
`

func (q *Queries) GetInvestigationSessionStartedAt(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getInvestigationSessionStartedAt, id)
	var started_at string
	err := row.Scan(&started_at)
	return started_at, err
}

const getInvestigationSessionStatsAverages = `-- name: GetInvestigationSessionStatsAverages :one
SELECT AVG(total_steps) AS avg_steps, AVG(duration_seconds) AS avg_duration
FROM investigation_sessions WHERE status != 'open'
`

type GetInvestigationSessionStatsAveragesRow struct {
	AvgSteps    sql.NullFloat64 `json:"avg_steps"`
	AvgDuration sql.NullFloat64 `json:"avg_duration"`
}

func (q *Queries) GetInvestigationSessionStatsAverages(ctx context.Context) (GetInvestigationSessionStatsAveragesRow, error) {
	row := q.db.QueryRowContext(ctx, getInvestigationSessionStatsAverages)
	var i GetInvestigationSessionStatsAveragesRow
	err := row.Scan(&i.AvgSteps, &i.AvgDuration)
	return i, err
}

const getInvestigationSessionStatsOpenSessions = `-- name: GetInvestigationSessionStatsOpenSessions :one
SELECT COUNT(*) FROM investigation_sessions WHERE status = 'open'
`

func (q *Queries) GetInvestigationSessionStatsOpenSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getInvestigationSessionStatsOpenSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInvestigationSessionStatsResolvedSessions = `-- name: GetInvestigationSessionStatsResolvedSessions :one
SELECT COUNT(*) FROM investigation_sessions WHERE status = 'resolved'
`

func (q *Queries) GetInvestigationSessionStatsResolvedSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getInvestigationSessionStatsResolvedSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInvestigationSessionStatsTotalSessions = `-- name: GetInvestigationSessionStatsTotalSessions :one
SELECT COUNT(*) FROM investigation_sessions
`

func (q *Queries) GetInvestigationSessionStatsTotalSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getInvestigationSessionStatsTotalSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInvestigationSessionToolSequence = `-- name: GetInvestigationSessionToolSequence :one
SELECT tool_sequence FROM investigation_sessions WHERE id = ?1
`

func (q *Queries) GetInvestigationSessionToolSequence(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getInvestigationSessionToolSequence, id)
	var tool_sequence string
	err := row.Scan(&tool_sequence)
	return tool_sequence, err
}

const pruneInvestigationSessions = `-- name: PruneInvestigationSessions :execrows
DELETE FROM investigation_sessions
WHERE rowid IN (SELECT i.rowid FROM investigation_sessions i WHERE i.ended_at IS NOT NULL AND i.ended_at < ?1 LIMIT 1000)
`

func (q *Queries) PruneInvestigationSessions(ctx context.Context, cutoff sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneInvestigationSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordInvestigationStep = `-- name: RecordInvestigationStep :exec
UPDATE investigation_sessions
SET total_steps = total_steps + 1,
    total_errors = total_errors + ?1,
    tool_sequence = ?2,
    tool_fingerprint = ?3,
    last_activity_at = ?4
WHERE id = ?5
`

type RecordInvestigationStepParams struct {
	ErrorIncrement  int64  `json:"error_increment"`
	ToolSequence    string `json:"tool_sequence"`
	ToolFingerprint string `json:"tool_fingerprint"`
	LastActivityAt  string `json:"last_activity_at"`
	ID              string `json:"id"`
}

func (q *Queries) RecordInvestigationStep(ctx context.Context, arg RecordInvestigationStepParams) error {
	_, err := q.db.ExecContext(ctx, recordInvestigationStep,
		arg.ErrorIncrement,
		arg.ToolSequence,
		arg.ToolFingerprint,
		arg.LastActivityAt,
		arg.ID,
	)
	return err
}
