// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journeys.sql

package db

import (
	"context"
	"database/sql"
)

const createFunnel = `-- name: CreateFunnel :exec
INSERT INTO funnels (name, service, steps, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type CreateFunnelParams struct {
	Name      string `json:"name"`
	Service   string `json:"service"`
	Steps     string `json:"steps"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateFunnel(ctx context.Context, arg CreateFunnelParams) error {
	_, err := q.db.ExecContext(ctx, createFunnel,
		arg.Name,
		arg.Service,
		arg.Steps,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFunnel = `-- name: DeleteFunnel :execrows
DELETE FROM funnels WHERE id = ?1
`

func (q *Queries) DeleteFunnel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFunnel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFunnel = `-- name: GetFunnel :one
SELECT id, name, service, steps, created_at, updated_at
FROM funnels WHERE id = ?1
`

func (q *Queries) GetFunnel(ctx context.Context, id int64) (Funnel, error) {
	row := q.db.QueryRowContext(ctx, getFunnel, id)
	var i Funnel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Service,
		&i.Steps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestTimeline = `-- name: GetRequestTimeline :one
SELECT l.id AS log_id, COALESCE(l.request_id, '') AS request_id,
       COALESCE(rs.controller, '') AS controller, COALESCE(rs."action", '') AS "action",
       COALESCE(rs.path, '') AS path,
       COALESCE(rs.status, 0) AS status, COALESCE(rs.duration_ms, 0) AS duration_ms,
       l.timestamp, rs.timeline
FROM logs l
JOIN request_summaries rs ON rs.log_id = l.id
WHERE l.id = ?1
`

type GetRequestTimelineRow struct {
	LogID      int64          `json:"log_id"`
	RequestID  string         `json:"request_id"`
	Controller string         `json:"controller"`
	Action     string         `json:"action"`
	Path       string         `json:"path"`
	Status     int64          `json:"status"`
	DurationMs float64        `json:"duration_ms"`
	Timestamp  string         `json:"timestamp"`
	Timeline   sql.NullString `json:"timeline"`
}

func (q *Queries) GetRequestTimeline(ctx context.Context, logID int64) (GetRequestTimelineRow, error) {
	row := q.db.QueryRowContext(ctx, getRequestTimeline, logID)
	var i GetRequestTimelineRow
	err := row.Scan(
		&i.LogID,
		&i.RequestID,
		&i.Controller,
		&i.Action,
		&i.Path,
		&i.Status,
		&i.DurationMs,
		&i.Timestamp,
		&i.Timeline,
	)
	return i, err
}

const getSession = `-- name: GetSession :one

SELECT id, session_id, user_id, service, environment,
       started_at, ended_at, request_count, error_count, total_duration_ms,
       entry_path, exit_path, exit_status, has_error, created_at
FROM user_sessions
WHERE session_id = ?1
`

// Journeys: user session tracking, funnels, and request timelines.
// Queries for user_sessions, funnels, and journey-related log/request_summary joins.
func (q *Queries) GetSession(ctx context.Context, sessionID string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Service,
		&i.Environment,
		&i.StartedAt,
		&i.EndedAt,
		&i.RequestCount,
		&i.ErrorCount,
		&i.TotalDurationMs,
		&i.EntryPath,
		&i.ExitPath,
		&i.ExitStatus,
		&i.HasError,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionRequests = `-- name: GetSessionRequests :many
SELECT l.timestamp, COALESCE(rs.controller, '') AS controller, COALESCE(rs."action", '') AS "action",
       COALESCE(rs.path, '') AS path, COALESCE(rs.method, '') AS method, COALESCE(rs.status, 0) AS status,
       COALESCE(rs.duration_ms, 0) AS duration_ms, COALESCE(rs.sql_count, 0) AS sql_count,
       CASE WHEN rs.status >= 500 THEN 1 ELSE 0 END AS has_error,
       COALESCE(l.exception_class, '') AS exception_class,
       COALESCE(l.request_id, '') AS request_id, l.id AS log_id
FROM logs l
JOIN request_summaries rs ON rs.log_id = l.id
WHERE l.session_id = ?1
ORDER BY l.timestamp ASC
`

type GetSessionRequestsRow struct {
	Timestamp      string  `json:"timestamp"`
	Controller     string  `json:"controller"`
	Action         string  `json:"action"`
	Path           string  `json:"path"`
	Method         string  `json:"method"`
	Status         int64   `json:"status"`
	DurationMs     float64 `json:"duration_ms"`
	SqlCount       int64   `json:"sql_count"`
	HasError       int64   `json:"has_error"`
	ExceptionClass string  `json:"exception_class"`
	RequestID      string  `json:"request_id"`
	LogID          int64   `json:"log_id"`
}

func (q *Queries) GetSessionRequests(ctx context.Context, sessionID sql.NullString) ([]GetSessionRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionRequests, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionRequestsRow{}
	for rows.Next() {
		var i GetSessionRequestsRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.Controller,
			&i.Action,
			&i.Path,
			&i.Method,
			&i.Status,
			&i.DurationMs,
			&i.SqlCount,
			&i.HasError,
			&i.ExceptionClass,
			&i.RequestID,
			&i.LogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionTimeline = `-- name: GetSessionTimeline :many
SELECT l.id AS log_id, COALESCE(l.request_id, '') AS request_id,
       COALESCE(rs.controller, '') AS controller, COALESCE(rs."action", '') AS "action",
       COALESCE(rs.path, '') AS path,
       COALESCE(rs.status, 0) AS status, COALESCE(rs.duration_ms, 0) AS duration_ms,
       l.timestamp, rs.timeline
FROM logs l
JOIN request_summaries rs ON rs.log_id = l.id
WHERE l.session_id = ?1
ORDER BY l.timestamp ASC
`

type GetSessionTimelineRow struct {
	LogID      int64          `json:"log_id"`
	RequestID  string         `json:"request_id"`
	Controller string         `json:"controller"`
	Action     string         `json:"action"`
	Path       string         `json:"path"`
	Status     int64          `json:"status"`
	DurationMs float64        `json:"duration_ms"`
	Timestamp  string         `json:"timestamp"`
	Timeline   sql.NullString `json:"timeline"`
}

func (q *Queries) GetSessionTimeline(ctx context.Context, sessionID sql.NullString) ([]GetSessionTimelineRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionTimeline, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionTimelineRow{}
	for rows.Next() {
		var i GetSessionTimelineRow
		if err := rows.Scan(
			&i.LogID,
			&i.RequestID,
			&i.Controller,
			&i.Action,
			&i.Path,
			&i.Status,
			&i.DurationMs,
			&i.Timestamp,
			&i.Timeline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFunnels = `-- name: ListFunnels :many
SELECT id, name, service, steps, created_at, updated_at
FROM funnels ORDER BY created_at DESC
`

func (q *Queries) ListFunnels(ctx context.Context) ([]Funnel, error) {
	rows, err := q.db.QueryContext(ctx, listFunnels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Funnel{}
	for rows.Next() {
		var i Funnel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Service,
			&i.Steps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
