// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package db

import (
	"context"
	"database/sql"
)

const getBatch = `-- name: GetBatch :one
SELECT batch_id, log_count, received_at FROM ingest_batches WHERE batch_id = ?1
`

func (q *Queries) GetBatch(ctx context.Context, batchID string) (IngestBatch, error) {
	row := q.db.QueryRowContext(ctx, getBatch, batchID)
	var i IngestBatch
	err := row.Scan(&i.BatchID, &i.LogCount, &i.ReceivedAt)
	return i, err
}

const getLogByID = `-- name: GetLogByID :one
SELECT id, timestamp, level, service, environment, commit_hash,
    trace_id, span_id, parent_span_id, request_id,
    user_id, session_id,
    message, event_type, exception_class, error_fingerprint,
    source_file, source_line, metadata
FROM logs WHERE id = ?1
`

type GetLogByIDRow struct {
	ID               int64          `json:"id"`
	Timestamp        string         `json:"timestamp"`
	Level            string         `json:"level"`
	Service          string         `json:"service"`
	Environment      sql.NullString `json:"environment"`
	CommitHash       sql.NullString `json:"commit_hash"`
	TraceID          sql.NullString `json:"trace_id"`
	SpanID           sql.NullString `json:"span_id"`
	ParentSpanID     sql.NullString `json:"parent_span_id"`
	RequestID        sql.NullString `json:"request_id"`
	UserID           sql.NullString `json:"user_id"`
	SessionID        sql.NullString `json:"session_id"`
	Message          string         `json:"message"`
	EventType        string         `json:"event_type"`
	ExceptionClass   sql.NullString `json:"exception_class"`
	ErrorFingerprint sql.NullString `json:"error_fingerprint"`
	SourceFile       sql.NullString `json:"source_file"`
	SourceLine       sql.NullInt64  `json:"source_line"`
	Metadata         sql.NullString `json:"metadata"`
}

func (q *Queries) GetLogByID(ctx context.Context, id int64) (GetLogByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLogByID, id)
	var i GetLogByIDRow
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Level,
		&i.Service,
		&i.Environment,
		&i.CommitHash,
		&i.TraceID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.RequestID,
		&i.UserID,
		&i.SessionID,
		&i.Message,
		&i.EventType,
		&i.ExceptionClass,
		&i.ErrorFingerprint,
		&i.SourceFile,
		&i.SourceLine,
		&i.Metadata,
	)
	return i, err
}

const insertLog = `-- name: InsertLog :exec

INSERT INTO logs (timestamp, level, service, environment, commit_hash,
    trace_id, span_id, parent_span_id, request_id,
    user_id, session_id,
    message, event_type, exception_class, error_fingerprint,
    source_file, source_line, metadata)
VALUES (?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9,
    ?10, ?11,
    ?12, ?13, ?14, ?15,
    ?16, ?17, ?18)
`

type InsertLogParams struct {
	Timestamp        string         `json:"timestamp"`
	Level            string         `json:"level"`
	Service          string         `json:"service"`
	Environment      sql.NullString `json:"environment"`
	CommitHash       sql.NullString `json:"commit_hash"`
	TraceID          sql.NullString `json:"trace_id"`
	SpanID           sql.NullString `json:"span_id"`
	ParentSpanID     sql.NullString `json:"parent_span_id"`
	RequestID        sql.NullString `json:"request_id"`
	UserID           sql.NullString `json:"user_id"`
	SessionID        sql.NullString `json:"session_id"`
	Message          string         `json:"message"`
	EventType        string         `json:"event_type"`
	ExceptionClass   sql.NullString `json:"exception_class"`
	ErrorFingerprint sql.NullString `json:"error_fingerprint"`
	SourceFile       sql.NullString `json:"source_file"`
	SourceLine       sql.NullInt64  `json:"source_line"`
	Metadata         sql.NullString `json:"metadata"`
}

// Logs: core log ingestion and retrieval.
// Only STATIC queries here; dynamic search/filter queries use squirrel.
func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog,
		arg.Timestamp,
		arg.Level,
		arg.Service,
		arg.Environment,
		arg.CommitHash,
		arg.TraceID,
		arg.SpanID,
		arg.ParentSpanID,
		arg.RequestID,
		arg.UserID,
		arg.SessionID,
		arg.Message,
		arg.EventType,
		arg.ExceptionClass,
		arg.ErrorFingerprint,
		arg.SourceFile,
		arg.SourceLine,
		arg.Metadata,
	)
	return err
}

const pruneBatches = `-- name: PruneBatches :execrows
DELETE FROM ingest_batches WHERE received_at < ?1
`

func (q *Queries) PruneBatches(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneBatches, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneLogs = `-- name: PruneLogs :execrows
DELETE FROM logs WHERE rowid IN (SELECT l.rowid FROM logs l WHERE l.timestamp < ?1 LIMIT 1000)
`

func (q *Queries) PruneLogs(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneLogs, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordBatch = `-- name: RecordBatch :exec
INSERT OR IGNORE INTO ingest_batches (batch_id, log_count) VALUES (?1, ?2)
`

type RecordBatchParams struct {
	BatchID  string `json:"batch_id"`
	LogCount int64  `json:"log_count"`
}

func (q *Queries) RecordBatch(ctx context.Context, arg RecordBatchParams) error {
	_, err := q.db.ExecContext(ctx, recordBatch, arg.BatchID, arg.LogCount)
	return err
}
