// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_activity.sql

package db

import (
	"context"
	"database/sql"
)

const getMCPActiveSessionCount = `-- name: GetMCPActiveSessionCount :one
SELECT COUNT(DISTINCT session_id) FROM mcp_activity
WHERE created_at > ?1
`

func (q *Queries) GetMCPActiveSessionCount(ctx context.Context, since string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMCPActiveSessionCount, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMCPCallCountSince = `-- name: GetMCPCallCountSince :one
SELECT COUNT(*) FROM mcp_activity
WHERE event_type = 'tool_call' AND created_at > ?1
`

func (q *Queries) GetMCPCallCountSince(ctx context.Context, since string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMCPCallCountSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMCPErrorCountSince = `-- name: GetMCPErrorCountSince :one
SELECT COUNT(*) FROM mcp_activity
WHERE event_type = 'tool_call' AND is_error = 1 AND created_at > ?1
`

func (q *Queries) GetMCPErrorCountSince(ctx context.Context, since string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMCPErrorCountSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMCPLastActivityTime = `-- name: GetMCPLastActivityTime :one
SELECT MAX(created_at) FROM mcp_activity
`

func (q *Queries) GetMCPLastActivityTime(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMCPLastActivityTime)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const insertMCPActivity = `-- name: InsertMCPActivity :exec

INSERT INTO mcp_activity (
    session_id, user_id, tool_name, arguments, result_preview,
    is_error, duration_ms, event_type,
    investigation_session_id, step_index,
    was_suggested, suggestion_rank, followed_by
)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5,
    ?6, ?7, ?8,
    ?9, ?10,
    ?11, ?12, ?13
)
`

type InsertMCPActivityParams struct {
	SessionID              string         `json:"session_id"`
	UserID                 sql.NullString `json:"user_id"`
	ToolName               string         `json:"tool_name"`
	Arguments              sql.NullString `json:"arguments"`
	ResultPreview          sql.NullString `json:"result_preview"`
	IsError                int64          `json:"is_error"`
	DurationMs             sql.NullInt64  `json:"duration_ms"`
	EventType              string         `json:"event_type"`
	InvestigationSessionID string         `json:"investigation_session_id"`
	StepIndex              int64          `json:"step_index"`
	WasSuggested           int64          `json:"was_suggested"`
	SuggestionRank         int64          `json:"suggestion_rank"`
	FollowedBy             string         `json:"followed_by"`
}

// MCP activity: tracks tool calls, connections, and disconnections from MCP clients.
func (q *Queries) InsertMCPActivity(ctx context.Context, arg InsertMCPActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertMCPActivity,
		arg.SessionID,
		arg.UserID,
		arg.ToolName,
		arg.Arguments,
		arg.ResultPreview,
		arg.IsError,
		arg.DurationMs,
		arg.EventType,
		arg.InvestigationSessionID,
		arg.StepIndex,
		arg.WasSuggested,
		arg.SuggestionRank,
		arg.FollowedBy,
	)
	return err
}

const listMCPActivityByInvestigationSession = `-- name: ListMCPActivityByInvestigationSession :many
SELECT id, session_id, COALESCE(user_id, '') AS user_id, tool_name,
       COALESCE(arguments, '') AS arguments,
       COALESCE(result_preview, '') AS result_preview,
       is_error, duration_ms, event_type, created_at
FROM mcp_activity
WHERE investigation_session_id = ?1
ORDER BY step_index ASC, created_at ASC
`

type ListMCPActivityByInvestigationSessionRow struct {
	ID            int64         `json:"id"`
	SessionID     string        `json:"session_id"`
	UserID        string        `json:"user_id"`
	ToolName      string        `json:"tool_name"`
	Arguments     string        `json:"arguments"`
	ResultPreview string        `json:"result_preview"`
	IsError       int64         `json:"is_error"`
	DurationMs    sql.NullInt64 `json:"duration_ms"`
	EventType     string        `json:"event_type"`
	CreatedAt     string        `json:"created_at"`
}

func (q *Queries) ListMCPActivityByInvestigationSession(ctx context.Context, investigationSessionID string) ([]ListMCPActivityByInvestigationSessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listMCPActivityByInvestigationSession, investigationSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPActivityByInvestigationSessionRow{}
	for rows.Next() {
		var i ListMCPActivityByInvestigationSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.ToolName,
			&i.Arguments,
			&i.ResultPreview,
			&i.IsError,
			&i.DurationMs,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMCPActivity = `-- name: ListRecentMCPActivity :many
SELECT id, session_id, COALESCE(user_id, '') AS user_id, tool_name,
       COALESCE(arguments, '') AS arguments,
       COALESCE(result_preview, '') AS result_preview,
       is_error, duration_ms, event_type, created_at
FROM mcp_activity
ORDER BY created_at DESC
LIMIT ?1
`

type ListRecentMCPActivityRow struct {
	ID            int64         `json:"id"`
	SessionID     string        `json:"session_id"`
	UserID        string        `json:"user_id"`
	ToolName      string        `json:"tool_name"`
	Arguments     string        `json:"arguments"`
	ResultPreview string        `json:"result_preview"`
	IsError       int64         `json:"is_error"`
	DurationMs    sql.NullInt64 `json:"duration_ms"`
	EventType     string        `json:"event_type"`
	CreatedAt     string        `json:"created_at"`
}

func (q *Queries) ListRecentMCPActivity(ctx context.Context, maxResults int64) ([]ListRecentMCPActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMCPActivity, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMCPActivityRow{}
	for rows.Next() {
		var i ListRecentMCPActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.ToolName,
			&i.Arguments,
			&i.ResultPreview,
			&i.IsError,
			&i.DurationMs,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneMCPActivity = `-- name: PruneMCPActivity :execrows
DELETE FROM mcp_activity
WHERE rowid IN (
    SELECT m.rowid FROM mcp_activity m WHERE m.created_at < ?1 LIMIT 1000
)
`

func (q *Queries) PruneMCPActivity(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneMCPActivity, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSuggestionTracking = `-- name: SetSuggestionTracking :exec
UPDATE mcp_activity
SET was_suggested = ?1, suggestion_rank = ?2
WHERE investigation_session_id = ?3 AND step_index = ?4
`

type SetSuggestionTrackingParams struct {
	WasSuggested           int64  `json:"was_suggested"`
	SuggestionRank         int64  `json:"suggestion_rank"`
	InvestigationSessionID string `json:"investigation_session_id"`
	StepIndex              int64  `json:"step_index"`
}

func (q *Queries) SetSuggestionTracking(ctx context.Context, arg SetSuggestionTrackingParams) error {
	_, err := q.db.ExecContext(ctx, setSuggestionTracking,
		arg.WasSuggested,
		arg.SuggestionRank,
		arg.InvestigationSessionID,
		arg.StepIndex,
	)
	return err
}

const updateFollowedBy = `-- name: UpdateFollowedBy :exec
UPDATE mcp_activity
SET followed_by = ?1
WHERE investigation_session_id = ?2 AND step_index = ?3
`

type UpdateFollowedByParams struct {
	FollowedBy             string `json:"followed_by"`
	InvestigationSessionID string `json:"investigation_session_id"`
	StepIndex              int64  `json:"step_index"`
}

func (q *Queries) UpdateFollowedBy(ctx context.Context, arg UpdateFollowedByParams) error {
	_, err := q.db.ExecContext(ctx, updateFollowedBy, arg.FollowedBy, arg.InvestigationSessionID, arg.StepIndex)
	return err
}
