// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"
	"database/sql"
)

const getLatestMetricsByServer = `-- name: GetLatestMetricsByServer :many
SELECT m.id, m.server_id, m.timestamp, m.metric_name, m.metric_value, m.unit, m.labels
FROM metrics m
INNER JOIN (
    SELECT m2.metric_name, MAX(m2.timestamp) AS max_ts
    FROM metrics m2
    WHERE m2.server_id = ?1
    GROUP BY m2.metric_name
) latest ON m.metric_name = latest.metric_name AND m.timestamp = latest.max_ts
WHERE m.server_id = ?1
ORDER BY m.metric_name
`

type GetLatestMetricsByServerRow struct {
	ID          int64          `json:"id"`
	ServerID    string         `json:"server_id"`
	Timestamp   string         `json:"timestamp"`
	MetricName  string         `json:"metric_name"`
	MetricValue float64        `json:"metric_value"`
	Unit        sql.NullString `json:"unit"`
	Labels      sql.NullString `json:"labels"`
}

func (q *Queries) GetLatestMetricsByServer(ctx context.Context, serverID string) ([]GetLatestMetricsByServerRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestMetricsByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLatestMetricsByServerRow{}
	for rows.Next() {
		var i GetLatestMetricsByServerRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Timestamp,
			&i.MetricName,
			&i.MetricValue,
			&i.Unit,
			&i.Labels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMetric = `-- name: InsertMetric :exec

INSERT INTO metrics (server_id, timestamp, metric_name, metric_value, unit, labels, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertMetricParams struct {
	ServerID    string         `json:"server_id"`
	Timestamp   string         `json:"timestamp"`
	MetricName  string         `json:"metric_name"`
	MetricValue float64        `json:"metric_value"`
	Unit        sql.NullString `json:"unit"`
	Labels      sql.NullString `json:"labels"`
	CreatedAt   string         `json:"created_at"`
}

// Metrics: time-series data points collected from server agents.
func (q *Queries) InsertMetric(ctx context.Context, arg InsertMetricParams) error {
	_, err := q.db.ExecContext(ctx, insertMetric,
		arg.ServerID,
		arg.Timestamp,
		arg.MetricName,
		arg.MetricValue,
		arg.Unit,
		arg.Labels,
		arg.CreatedAt,
	)
	return err
}

const pruneMetrics = `-- name: PruneMetrics :execrows
DELETE FROM metrics
WHERE rowid IN (
    SELECT m3.rowid FROM metrics m3 WHERE m3.created_at < ?1 LIMIT 1000
)
`

func (q *Queries) PruneMetrics(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneMetrics, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
