// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AgentNote struct {
	ID         int64  `json:"id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Note       string `json:"note"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type AppConfig struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type AuditLog struct {
	ID         int64          `json:"id"`
	UserID     string         `json:"user_id"`
	UserEmail  string         `json:"user_email"`
	Action     string         `json:"action"`
	TargetType sql.NullString `json:"target_type"`
	TargetID   sql.NullString `json:"target_id"`
	Details    sql.NullString `json:"details"`
	IpAddress  sql.NullString `json:"ip_address"`
	CreatedAt  string         `json:"created_at"`
}

type CodeEntity struct {
	ID                  int64           `json:"id"`
	EntityType          string          `json:"entity_type"`
	EntityName          string          `json:"entity_name"`
	Service             string          `json:"service"`
	RiskScore           float64         `json:"risk_score"`
	ErrorCount          int64           `json:"error_count"`
	InvestigationCount  int64           `json:"investigation_count"`
	AvgDurationMs       sql.NullFloat64 `json:"avg_duration_ms"`
	LastErrorAt         sql.NullString  `json:"last_error_at"`
	LastInvestigationAt sql.NullString  `json:"last_investigation_at"`
	MetadataJson        string          `json:"metadata_json"`
	CreatedAt           string          `json:"created_at"`
	UpdatedAt           string          `json:"updated_at"`
}

type DataSource struct {
	ID            string         `json:"id"`
	Type          string         `json:"type"`
	Name          string         `json:"name"`
	Config        string         `json:"config"`
	Status        string         `json:"status"`
	StatusMessage sql.NullString `json:"status_message"`
	LastTestedAt  sql.NullString `json:"last_tested_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
	Environment   string         `json:"environment"`
}

type Deploy struct {
	ID                         int64           `json:"id"`
	Service                    string          `json:"service"`
	Environment                string          `json:"environment"`
	CommitHash                 string          `json:"commit_hash"`
	Branch                     string          `json:"branch"`
	Author                     string          `json:"author"`
	FilesChangedJson           string          `json:"files_changed_json"`
	DeploySource               string          `json:"deploy_source"`
	PreErrorRate               sql.NullFloat64 `json:"pre_error_rate"`
	PostErrorRate              sql.NullFloat64 `json:"post_error_rate"`
	PreAvgDurationMs           sql.NullFloat64 `json:"pre_avg_duration_ms"`
	PostAvgDurationMs          sql.NullFloat64 `json:"post_avg_duration_ms"`
	ImpactMeasuredAt           sql.NullString  `json:"impact_measured_at"`
	LinkedInvestigationIdsJson string          `json:"linked_investigation_ids_json"`
	Status                     string          `json:"status"`
	DeployedAt                 string          `json:"deployed_at"`
	CreatedAt                  string          `json:"created_at"`
}

type DeployMarker struct {
	ID           int64  `json:"id"`
	Service      string `json:"service"`
	Environment  string `json:"environment"`
	CommitHash   string `json:"commit_hash"`
	FirstSeenAt  string `json:"first_seen_at"`
	RequestCount int64  `json:"request_count"`
}

type EndpointStat struct {
	ID               int64   `json:"id"`
	Period           string  `json:"period"`
	PeriodStart      string  `json:"period_start"`
	Service          string  `json:"service"`
	Method           string  `json:"method"`
	Controller       string  `json:"controller"`
	Action           string  `json:"action"`
	PathPattern      string  `json:"path_pattern"`
	RequestCount     int64   `json:"request_count"`
	ErrorCount       int64   `json:"error_count"`
	ClientErrorCount int64   `json:"client_error_count"`
	AvgDurationMs    float64 `json:"avg_duration_ms"`
	P95DurationMs    float64 `json:"p95_duration_ms"`
	MaxDurationMs    float64 `json:"max_duration_ms"`
	AvgSqlCount      float64 `json:"avg_sql_count"`
	Status2xx        int64   `json:"status_2xx"`
	Status3xx        int64   `json:"status_3xx"`
	Status4xx        int64   `json:"status_4xx"`
	Status5xx        int64   `json:"status_5xx"`
	CreatedAt        string  `json:"created_at"`
}

type ErrorGroup struct {
	Fingerprint     string         `json:"fingerprint"`
	Service         string         `json:"service"`
	Environment     string         `json:"environment"`
	ExceptionClass  string         `json:"exception_class"`
	Message         string         `json:"message"`
	SourceFile      string         `json:"source_file"`
	SourceLine      int64          `json:"source_line"`
	Status          string         `json:"status"`
	FirstSeenAt     string         `json:"first_seen_at"`
	LastSeenAt      string         `json:"last_seen_at"`
	OccurrenceCount int64          `json:"occurrence_count"`
	LastLogID       sql.NullInt64  `json:"last_log_id"`
	ReopenedCount   int64          `json:"reopened_count"`
	ResolvedAt      sql.NullString `json:"resolved_at"`
	IgnoredAt       sql.NullString `json:"ignored_at"`
	UniqueUsers     int64          `json:"unique_users"`
	ImpactScore     float64        `json:"impact_score"`
	CommonContext   string         `json:"common_context"`
}

type ErrorGroupEvent struct {
	ID          int64  `json:"id"`
	Fingerprint string `json:"fingerprint"`
	Action      string `json:"action"`
	Reason      string `json:"reason"`
	CreatedAt   string `json:"created_at"`
}

type ErrorImpact struct {
	ID               int64  `json:"id"`
	ErrorFingerprint string `json:"error_fingerprint"`
	UserID           string `json:"user_id"`
	Service          string `json:"service"`
	FirstSeenAt      string `json:"first_seen_at"`
	LastSeenAt       string `json:"last_seen_at"`
	OccurrenceCount  int64  `json:"occurrence_count"`
	LastContext      string `json:"last_context"`
	LastLogID        int64  `json:"last_log_id"`
}

type Event struct {
	ID           int64  `json:"id"`
	EventType    string `json:"event_type"`
	Source       string `json:"source"`
	Service      string `json:"service"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	MetadataJson string `json:"metadata_json"`
	ExternalID   string `json:"external_id"`
	ExternalUrl  string `json:"external_url"`
	Author       string `json:"author"`
	CreatedAt    string `json:"created_at"`
}

type Funnel struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Service   string `json:"service"`
	Steps     string `json:"steps"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Healthcheck struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Url            string `json:"url"`
	Method         string `json:"method"`
	IntervalSecs   int64  `json:"interval_secs"`
	TimeoutSecs    int64  `json:"timeout_secs"`
	ExpectedStatus int64  `json:"expected_status"`
	Enabled        int64  `json:"enabled"`
	CreatedAt      string `json:"created_at"`
	ExpectedBody   string `json:"expected_body"`
	Retries        int64  `json:"retries"`
}

type HealthcheckResult struct {
	ID            int64         `json:"id"`
	HealthcheckID string        `json:"healthcheck_id"`
	Status        string        `json:"status"`
	StatusCode    sql.NullInt64 `json:"status_code"`
	ResponseMs    sql.NullInt64 `json:"response_ms"`
	Error         string        `json:"error"`
	CheckedAt     string        `json:"checked_at"`
}

type IngestBatch struct {
	BatchID    string `json:"batch_id"`
	LogCount   int64  `json:"log_count"`
	ReceivedAt string `json:"received_at"`
}

type InvestigationSession struct {
	ID                            string         `json:"id"`
	UserID                        string         `json:"user_id"`
	UserEmail                     string         `json:"user_email"`
	UserRole                      string         `json:"user_role"`
	ClientName                    string         `json:"client_name"`
	ClientVersion                 string         `json:"client_version"`
	Workspace                     string         `json:"workspace"`
	Transport                     string         `json:"transport"`
	ConnectionID                  string         `json:"connection_id"`
	Intent                        string         `json:"intent"`
	IntentDetail                  string         `json:"intent_detail"`
	PrimaryService                string         `json:"primary_service"`
	PrimaryDatasourceID           sql.NullInt64  `json:"primary_datasource_id"`
	Status                        string         `json:"status"`
	Summary                       string         `json:"summary"`
	RootCause                     string         `json:"root_cause"`
	FixDescription                string         `json:"fix_description"`
	CreatedWatcherIds             string         `json:"created_watcher_ids"`
	TriggeredByAlertID            sql.NullString `json:"triggered_by_alert_id"`
	TriggeredByWatcherID          sql.NullString `json:"triggered_by_watcher_id"`
	ResolvedErrorGroupIds         string         `json:"resolved_error_group_ids"`
	InvestigatedErrorFingerprints string         `json:"investigated_error_fingerprints"`
	CreatedHealthcheckIds         string         `json:"created_healthcheck_ids"`
	TriggeredByHealthcheckID      sql.NullString `json:"triggered_by_healthcheck_id"`
	CreatedNoteIds                string         `json:"created_note_ids"`
	AutoNoteIds                   string         `json:"auto_note_ids"`
	RunbooksExecuted              string         `json:"runbooks_executed"`
	ExplainedQueries              string         `json:"explained_queries"`
	KilledQueries                 string         `json:"killed_queries"`
	TraceIds                      string         `json:"trace_ids"`
	CorrelatedDeploy              string         `json:"correlated_deploy"`
	PreInvestigationSnapshot      string         `json:"pre_investigation_snapshot"`
	PostInvestigationSnapshot     string         `json:"post_investigation_snapshot"`
	TotalSteps                    int64          `json:"total_steps"`
	TotalErrors                   int64          `json:"total_errors"`
	ToolSequence                  string         `json:"tool_sequence"`
	ToolFingerprint               string         `json:"tool_fingerprint"`
	ArgSignature                  string         `json:"arg_signature"`
	StartedAt                     string         `json:"started_at"`
	LastActivityAt                string         `json:"last_activity_at"`
	EndedAt                       sql.NullString `json:"ended_at"`
	DurationSeconds               int64          `json:"duration_seconds"`
	RecurrenceGroup               sql.NullString `json:"recurrence_group"`
	RecurrenceCount               int64          `json:"recurrence_count"`
	PreviousSessionID             sql.NullString `json:"previous_session_id"`
	FixDurabilitySeconds          sql.NullInt64  `json:"fix_durability_seconds"`
	FilesModified                 string         `json:"files_modified"`
	FilesRead                     string         `json:"files_read"`
	LinkedDeployID                sql.NullInt64  `json:"linked_deploy_id"`
}

type Job struct {
	ID          int64          `json:"id"`
	Queue       string         `json:"queue"`
	JobType     string         `json:"job_type"`
	Payload     string         `json:"payload"`
	Status      string         `json:"status"`
	Priority    int64          `json:"priority"`
	Attempts    int64          `json:"attempts"`
	MaxAttempts int64          `json:"max_attempts"`
	RunAt       string         `json:"run_at"`
	StartedAt   sql.NullString `json:"started_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	LastError   sql.NullString `json:"last_error"`
	CreatedAt   string         `json:"created_at"`
}

type Log struct {
	ID               int64          `json:"id"`
	Timestamp        string         `json:"timestamp"`
	Level            string         `json:"level"`
	Service          string         `json:"service"`
	TraceID          sql.NullString `json:"trace_id"`
	Message          string         `json:"message"`
	Environment      sql.NullString `json:"environment"`
	Metadata         sql.NullString `json:"metadata"`
	EventType        string         `json:"event_type"`
	SpanID           sql.NullString `json:"span_id"`
	ParentSpanID     sql.NullString `json:"parent_span_id"`
	CommitHash       sql.NullString `json:"commit_hash"`
	RequestID        sql.NullString `json:"request_id"`
	ExceptionClass   sql.NullString `json:"exception_class"`
	ErrorFingerprint sql.NullString `json:"error_fingerprint"`
	SourceFile       sql.NullString `json:"source_file"`
	SourceLine       sql.NullInt64  `json:"source_line"`
	UserID           sql.NullString `json:"user_id"`
	SessionID        sql.NullString `json:"session_id"`
}

type LogsFt struct {
	Message string `json:"message"`
}

type McpActivity struct {
	ID                     int64          `json:"id"`
	SessionID              string         `json:"session_id"`
	UserID                 sql.NullString `json:"user_id"`
	ToolName               string         `json:"tool_name"`
	Arguments              sql.NullString `json:"arguments"`
	ResultPreview          sql.NullString `json:"result_preview"`
	IsError                int64          `json:"is_error"`
	DurationMs             sql.NullInt64  `json:"duration_ms"`
	EventType              string         `json:"event_type"`
	CreatedAt              string         `json:"created_at"`
	InvestigationSessionID string         `json:"investigation_session_id"`
	StepIndex              int64          `json:"step_index"`
	WasSuggested           int64          `json:"was_suggested"`
	SuggestionRank         int64          `json:"suggestion_rank"`
	FollowedBy             string         `json:"followed_by"`
}

type Metric struct {
	ID          int64          `json:"id"`
	ServerID    string         `json:"server_id"`
	Timestamp   string         `json:"timestamp"`
	MetricName  string         `json:"metric_name"`
	MetricValue float64        `json:"metric_value"`
	Unit        sql.NullString `json:"unit"`
	Labels      sql.NullString `json:"labels"`
	CreatedAt   string         `json:"created_at"`
}

type MetricBucket struct {
	ID                int64   `json:"id"`
	BucketStart       string  `json:"bucket_start"`
	BucketInterval    string  `json:"bucket_interval"`
	Service           string  `json:"service"`
	Endpoint          string  `json:"endpoint"`
	Environment       string  `json:"environment"`
	RequestCount      int64   `json:"request_count"`
	ErrorCount        int64   `json:"error_count"`
	LogCount          int64   `json:"log_count"`
	AvgDurationMs     float64 `json:"avg_duration_ms"`
	P50DurationMs     float64 `json:"p50_duration_ms"`
	P95DurationMs     float64 `json:"p95_duration_ms"`
	P99DurationMs     float64 `json:"p99_duration_ms"`
	MaxDurationMs     float64 `json:"max_duration_ms"`
	AvgSqlCount       float64 `json:"avg_sql_count"`
	AvgDbTimeMs       float64 `json:"avg_db_time_ms"`
	AvgCacheHitRatio  float64 `json:"avg_cache_hit_ratio"`
	AvgHttpExternalMs float64 `json:"avg_http_external_ms"`
	CreatedAt         string  `json:"created_at"`
}

type QueryMemory struct {
	Fingerprint                string        `json:"fingerprint"`
	LastInvestigationSessionID string        `json:"last_investigation_session_id"`
	InvestigationCount         int64         `json:"investigation_count"`
	LastRootCause              string        `json:"last_root_cause"`
	LastFix                    string        `json:"last_fix"`
	AvgDurationBeforeMs        sql.NullInt64 `json:"avg_duration_before_ms"`
	AvgDurationAfterMs         sql.NullInt64 `json:"avg_duration_after_ms"`
	FirstSeenAt                string        `json:"first_seen_at"`
	LastSeenAt                 string        `json:"last_seen_at"`
}

type RequestSummary struct {
	ID                  int64           `json:"id"`
	LogID               int64           `json:"log_id"`
	Controller          sql.NullString  `json:"controller"`
	Action              sql.NullString  `json:"action"`
	Method              sql.NullString  `json:"method"`
	Path                sql.NullString  `json:"path"`
	Status              sql.NullInt64   `json:"status"`
	DurationMs          sql.NullFloat64 `json:"duration_ms"`
	DbTimeMs            sql.NullFloat64 `json:"db_time_ms"`
	ViewTimeMs          sql.NullFloat64 `json:"view_time_ms"`
	SqlCount            sql.NullInt64   `json:"sql_count"`
	SqlTotalMs          sql.NullFloat64 `json:"sql_total_ms"`
	SqlSlowestMs        sql.NullFloat64 `json:"sql_slowest_ms"`
	SqlSlowestName      sql.NullString  `json:"sql_slowest_name"`
	NPlusOne            sql.NullInt64   `json:"n_plus_one"`
	ViewCount           sql.NullInt64   `json:"view_count"`
	ViewTotalMs         sql.NullFloat64 `json:"view_total_ms"`
	ViewSlowestMs       sql.NullFloat64 `json:"view_slowest_ms"`
	ViewSlowestTemplate sql.NullString  `json:"view_slowest_template"`
	CacheReads          sql.NullInt64   `json:"cache_reads"`
	CacheHits           sql.NullInt64   `json:"cache_hits"`
	CacheWrites         sql.NullInt64   `json:"cache_writes"`
	CacheHitRatio       sql.NullFloat64 `json:"cache_hit_ratio"`
	HttpExternalCount   sql.NullInt64   `json:"http_external_count"`
	HttpExternalTotalMs sql.NullFloat64 `json:"http_external_total_ms"`
	HttpSlowestMs       sql.NullFloat64 `json:"http_slowest_ms"`
	HttpSlowestHost     sql.NullString  `json:"http_slowest_host"`
	MemoryBeforeMb      sql.NullFloat64 `json:"memory_before_mb"`
	MemoryAfterMb       sql.NullFloat64 `json:"memory_after_mb"`
	MemoryDeltaMb       sql.NullFloat64 `json:"memory_delta_mb"`
	Timeline            sql.NullString  `json:"timeline"`
	CreatedAt           string          `json:"created_at"`
	TimeBreakdown       sql.NullString  `json:"time_breakdown"`
	DuplicateQueries    sql.NullInt64   `json:"duplicate_queries"`
	WorstDuplicateCount sql.NullInt64   `json:"worst_duplicate_count"`
	TopDuplicates       sql.NullString  `json:"top_duplicates"`
}

type RunbookEffectiveness struct {
	RunbookName               string `json:"runbook_name"`
	TotalExecutions           int64  `json:"total_executions"`
	ResolvedSessions          int64  `json:"resolved_sessions"`
	AbandonedSessions         int64  `json:"abandoned_sessions"`
	AvgStepsAfter             int64  `json:"avg_steps_after"`
	AvgSessionDurationSeconds int64  `json:"avg_session_duration_seconds"`
	LastExecutedAt            string `json:"last_executed_at"`
}

type Server struct {
	ID           string         `json:"id"`
	Hostname     string         `json:"hostname"`
	IpAddress    sql.NullString `json:"ip_address"`
	Os           sql.NullString `json:"os"`
	Arch         sql.NullString `json:"arch"`
	AgentVersion sql.NullString `json:"agent_version"`
	Labels       sql.NullString `json:"labels"`
	Status       string         `json:"status"`
	LastSeenAt   sql.NullString `json:"last_seen_at"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	DisplayName  sql.NullString `json:"display_name"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type ToolTransition struct {
	FromTool       string `json:"from_tool"`
	ToTool         string `json:"to_tool"`
	Intent         string `json:"intent"`
	TotalCount     int64  `json:"total_count"`
	ResolvedCount  int64  `json:"resolved_count"`
	AbandonedCount int64  `json:"abandoned_count"`
	AvgDurationMs  int64  `json:"avg_duration_ms"`
	LastSeenAt     string `json:"last_seen_at"`
}

type TraceStatus struct {
	TraceID       string         `json:"trace_id"`
	SpanCount     int64          `json:"span_count"`
	RootSpanID    sql.NullString `json:"root_span_id"`
	Services      string         `json:"services"`
	FirstSeenAt   string         `json:"first_seen_at"`
	LastUpdatedAt string         `json:"last_updated_at"`
	DurationMs    float64        `json:"duration_ms"`
	Status        string         `json:"status"`
	HasErrors     int64          `json:"has_errors"`
}

type TrafficHeatmap struct {
	Service       string  `json:"service"`
	DayOfWeek     int64   `json:"day_of_week"`
	HourOfDay     int64   `json:"hour_of_day"`
	RequestCount  int64   `json:"request_count"`
	ErrorCount    int64   `json:"error_count"`
	AvgDurationMs float64 `json:"avg_duration_ms"`
	UpdatedAt     string  `json:"updated_at"`
}

type UncoveredErrorPath struct {
	ID                 int64   `json:"id"`
	Service            string  `json:"service"`
	ErrorFingerprint   string  `json:"error_fingerprint"`
	ErrorClass         string  `json:"error_class"`
	SourceFile         string  `json:"source_file"`
	Endpoint           string  `json:"endpoint"`
	ErrorCount         int64   `json:"error_count"`
	UserImpactScore    float64 `json:"user_impact_score"`
	InvestigationCount int64   `json:"investigation_count"`
	PriorityScore      float64 `json:"priority_score"`
	LastSeenAt         string  `json:"last_seen_at"`
	CreatedAt          string  `json:"created_at"`
	UpdatedAt          string  `json:"updated_at"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	DisplayName  string         `json:"display_name"`
	Role         string         `json:"role"`
	McpEnabled   int64          `json:"mcp_enabled"`
	McpToken     sql.NullString `json:"mcp_token"`
	IsActive     int64          `json:"is_active"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type UserSession struct {
	ID              int64   `json:"id"`
	SessionID       string  `json:"session_id"`
	UserID          string  `json:"user_id"`
	Service         string  `json:"service"`
	Environment     string  `json:"environment"`
	StartedAt       string  `json:"started_at"`
	EndedAt         string  `json:"ended_at"`
	RequestCount    int64   `json:"request_count"`
	ErrorCount      int64   `json:"error_count"`
	TotalDurationMs float64 `json:"total_duration_ms"`
	EntryPath       string  `json:"entry_path"`
	ExitPath        string  `json:"exit_path"`
	ExitStatus      int64   `json:"exit_status"`
	HasError        int64   `json:"has_error"`
	CreatedAt       string  `json:"created_at"`
}

type Watch struct {
	ID                  string          `json:"id"`
	Metric              string          `json:"metric"`
	Operator            string          `json:"operator"`
	Threshold           float64         `json:"threshold"`
	Service             string          `json:"service"`
	Endpoint            string          `json:"endpoint"`
	Environment         string          `json:"environment"`
	CommitHash          string          `json:"commit_hash"`
	Duration            string          `json:"duration"`
	Urgency             string          `json:"urgency"`
	CheckInterval       string          `json:"check_interval"`
	BaselineWindow      string          `json:"baseline_window"`
	MinConsecutive      int64           `json:"min_consecutive"`
	Status              string          `json:"status"`
	BaselineJson        sql.NullString  `json:"baseline_json"`
	ConsecutiveBreaches int64           `json:"consecutive_breaches"`
	CurrentValue        sql.NullFloat64 `json:"current_value"`
	ExpiresAt           sql.NullString  `json:"expires_at"`
	CreatedBy           string          `json:"created_by"`
	SessionID           string          `json:"session_id"`
	LastCheckedAt       sql.NullString  `json:"last_checked_at"`
	NextCheckAt         sql.NullString  `json:"next_check_at"`
	CreatedAt           string          `json:"created_at"`
	UpdatedAt           string          `json:"updated_at"`
}

type WatchAlert struct {
	ID             string         `json:"id"`
	WatchID        string         `json:"watch_id"`
	RunID          sql.NullString `json:"run_id"`
	Urgency        string         `json:"urgency"`
	Summary        string         `json:"summary"`
	TriggerMetric  string         `json:"trigger_metric"`
	TriggerValue   float64        `json:"trigger_value"`
	ThresholdValue float64        `json:"threshold_value"`
	EvidenceJson   sql.NullString `json:"evidence_json"`
	Status         string         `json:"status"`
	DismissReason  sql.NullString `json:"dismiss_reason"`
	CreatedAt      string         `json:"created_at"`
}

type WatchRun struct {
	ID           string          `json:"id"`
	WatchID      string          `json:"watch_id"`
	Status       string          `json:"status"`
	MetricValue  sql.NullFloat64 `json:"metric_value"`
	Breached     int64           `json:"breached"`
	Summary      sql.NullString  `json:"summary"`
	ErrorMessage sql.NullString  `json:"error_message"`
	StartedAt    string          `json:"started_at"`
	FinishedAt   sql.NullString  `json:"finished_at"`
}

type WorkflowTemplate struct {
	ID                   int64  `json:"id"`
	Intent               string `json:"intent"`
	Name                 string `json:"name"`
	StepOrder            int64  `json:"step_order"`
	ToolName             string `json:"tool_name"`
	ArgsHint             string `json:"args_hint"`
	Source               string `json:"source"`
	ResolvedSessionCount int64  `json:"resolved_session_count"`
	CreatedAt            string `json:"created_at"`
}
