// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_memory.sql

package db

import (
	"context"
	"database/sql"
)

const getQueryMemory = `-- name: GetQueryMemory :one

SELECT fingerprint, last_investigation_session_id, investigation_count,
       last_root_cause, last_fix, avg_duration_before_ms, avg_duration_after_ms,
       first_seen_at, last_seen_at
FROM query_memory WHERE fingerprint = ?1
`

// Query memory: stores explain_query findings across investigation sessions.
// Table: query_memory (migration 000041)
func (q *Queries) GetQueryMemory(ctx context.Context, fingerprint string) (QueryMemory, error) {
	row := q.db.QueryRowContext(ctx, getQueryMemory, fingerprint)
	var i QueryMemory
	err := row.Scan(
		&i.Fingerprint,
		&i.LastInvestigationSessionID,
		&i.InvestigationCount,
		&i.LastRootCause,
		&i.LastFix,
		&i.AvgDurationBeforeMs,
		&i.AvgDurationAfterMs,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const pruneQueryMemory = `-- name: PruneQueryMemory :execrows
DELETE FROM query_memory WHERE last_seen_at < ?1
`

func (q *Queries) PruneQueryMemory(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneQueryMemory, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertQueryMemory = `-- name: UpsertQueryMemory :exec
INSERT INTO query_memory (fingerprint, last_investigation_session_id, investigation_count,
                          last_root_cause, last_fix, avg_duration_before_ms,
                          first_seen_at, last_seen_at)
VALUES (?1, ?2, 1,
        ?3, ?4, ?5,
        ?6, ?6)
ON CONFLICT(fingerprint) DO UPDATE SET
    investigation_count = investigation_count + 1,
    last_investigation_session_id = sqlc.arg(session_id),
    last_root_cause = CASE WHEN sqlc.arg(root_cause) != '' THEN sqlc.arg(root_cause) ELSE last_root_cause END,
    last_fix = CASE WHEN sqlc.arg(fix) != '' THEN sqlc.arg(fix) ELSE last_fix END,
    last_seen_at = sqlc.arg(now)
`

type UpsertQueryMemoryParams struct {
	Fingerprint string        `json:"fingerprint"`
	SessionID   string        `json:"session_id"`
	RootCause   string        `json:"root_cause"`
	Fix         string        `json:"fix"`
	DurationMs  sql.NullInt64 `json:"duration_ms"`
	Now         string        `json:"now"`
}

func (q *Queries) UpsertQueryMemory(ctx context.Context, arg UpsertQueryMemoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertQueryMemory,
		arg.Fingerprint,
		arg.SessionID,
		arg.RootCause,
		arg.Fix,
		arg.DurationMs,
		arg.Now,
	)
	return err
}
