// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runbook_effectiveness.sql

package db

import (
	"context"
)

const getMostEffectiveRunbook = `-- name: GetMostEffectiveRunbook :one
SELECT runbook_name, total_executions, resolved_sessions, abandoned_sessions,
       avg_steps_after, avg_session_duration_seconds, last_executed_at
FROM runbook_effectiveness
WHERE total_executions >= 3 AND resolved_sessions > abandoned_sessions
ORDER BY CAST(resolved_sessions AS REAL) / total_executions DESC
LIMIT 1
`

func (q *Queries) GetMostEffectiveRunbook(ctx context.Context) (RunbookEffectiveness, error) {
	row := q.db.QueryRowContext(ctx, getMostEffectiveRunbook)
	var i RunbookEffectiveness
	err := row.Scan(
		&i.RunbookName,
		&i.TotalExecutions,
		&i.ResolvedSessions,
		&i.AbandonedSessions,
		&i.AvgStepsAfter,
		&i.AvgSessionDurationSeconds,
		&i.LastExecutedAt,
	)
	return i, err
}

const listRunbookEffectiveness = `-- name: ListRunbookEffectiveness :many
SELECT runbook_name, total_executions, resolved_sessions, abandoned_sessions,
       avg_steps_after, avg_session_duration_seconds, last_executed_at
FROM runbook_effectiveness
ORDER BY total_executions DESC
LIMIT 100
`

func (q *Queries) ListRunbookEffectiveness(ctx context.Context) ([]RunbookEffectiveness, error) {
	rows, err := q.db.QueryContext(ctx, listRunbookEffectiveness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunbookEffectiveness{}
	for rows.Next() {
		var i RunbookEffectiveness
		if err := rows.Scan(
			&i.RunbookName,
			&i.TotalExecutions,
			&i.ResolvedSessions,
			&i.AbandonedSessions,
			&i.AvgStepsAfter,
			&i.AvgSessionDurationSeconds,
			&i.LastExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRunbookExecution = `-- name: RecordRunbookExecution :exec

INSERT INTO runbook_effectiveness (runbook_name, total_executions, last_executed_at)
VALUES (?1, 1, ?2)
ON CONFLICT(runbook_name) DO UPDATE SET
    total_executions = total_executions + 1,
    last_executed_at = sqlc.arg(now)
`

type RecordRunbookExecutionParams struct {
	RunbookName string `json:"runbook_name"`
	Now         string `json:"now"`
}

// Runbook effectiveness: tracks resolution rates per playbook.
// Table: runbook_effectiveness (migration 000041)
func (q *Queries) RecordRunbookExecution(ctx context.Context, arg RecordRunbookExecutionParams) error {
	_, err := q.db.ExecContext(ctx, recordRunbookExecution, arg.RunbookName, arg.Now)
	return err
}

const updateRunbookOutcomeAbandoned = `-- name: UpdateRunbookOutcomeAbandoned :exec
UPDATE runbook_effectiveness SET
    abandoned_sessions = abandoned_sessions + 1,
    avg_steps_after = (avg_steps_after * abandoned_sessions + ?1) / (abandoned_sessions + 1),
    avg_session_duration_seconds = (avg_session_duration_seconds * abandoned_sessions + ?2) / (abandoned_sessions + 1)
WHERE runbook_name = ?3
`

type UpdateRunbookOutcomeAbandonedParams struct {
	StepsAfter  int64  `json:"steps_after"`
	DurationSec int64  `json:"duration_sec"`
	RunbookName string `json:"runbook_name"`
}

func (q *Queries) UpdateRunbookOutcomeAbandoned(ctx context.Context, arg UpdateRunbookOutcomeAbandonedParams) error {
	_, err := q.db.ExecContext(ctx, updateRunbookOutcomeAbandoned, arg.StepsAfter, arg.DurationSec, arg.RunbookName)
	return err
}

const updateRunbookOutcomeResolved = `-- name: UpdateRunbookOutcomeResolved :exec
UPDATE runbook_effectiveness SET
    resolved_sessions = resolved_sessions + 1,
    avg_steps_after = (avg_steps_after * resolved_sessions + ?1) / (resolved_sessions + 1),
    avg_session_duration_seconds = (avg_session_duration_seconds * resolved_sessions + ?2) / (resolved_sessions + 1)
WHERE runbook_name = ?3
`

type UpdateRunbookOutcomeResolvedParams struct {
	StepsAfter  int64  `json:"steps_after"`
	DurationSec int64  `json:"duration_sec"`
	RunbookName string `json:"runbook_name"`
}

func (q *Queries) UpdateRunbookOutcomeResolved(ctx context.Context, arg UpdateRunbookOutcomeResolvedParams) error {
	_, err := q.db.ExecContext(ctx, updateRunbookOutcomeResolved, arg.StepsAfter, arg.DurationSec, arg.RunbookName)
	return err
}
