// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package db

import (
	"context"
	"database/sql"
)

const deleteServer = `-- name: DeleteServer :execrows
DELETE FROM servers
WHERE id = ?1
`

func (q *Queries) DeleteServer(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteServer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, hostname, display_name, ip_address, os, arch, agent_version, labels, status, last_seen_at, created_at, updated_at
FROM servers
WHERE id = ?1
`

type GetServerByIDRow struct {
	ID           string         `json:"id"`
	Hostname     string         `json:"hostname"`
	DisplayName  sql.NullString `json:"display_name"`
	IpAddress    sql.NullString `json:"ip_address"`
	Os           sql.NullString `json:"os"`
	Arch         sql.NullString `json:"arch"`
	AgentVersion sql.NullString `json:"agent_version"`
	Labels       sql.NullString `json:"labels"`
	Status       string         `json:"status"`
	LastSeenAt   sql.NullString `json:"last_seen_at"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) GetServerByID(ctx context.Context, id string) (GetServerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getServerByID, id)
	var i GetServerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.DisplayName,
		&i.IpAddress,
		&i.Os,
		&i.Arch,
		&i.AgentVersion,
		&i.Labels,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, hostname, display_name, ip_address, os, arch, agent_version, labels, status, last_seen_at, created_at, updated_at
FROM servers
ORDER BY hostname ASC
LIMIT ?2 OFFSET ?1
`

type ListServersParams struct {
	RowOffset int64 `json:"row_offset"`
	RowLimit  int64 `json:"row_limit"`
}

type ListServersRow struct {
	ID           string         `json:"id"`
	Hostname     string         `json:"hostname"`
	DisplayName  sql.NullString `json:"display_name"`
	IpAddress    sql.NullString `json:"ip_address"`
	Os           sql.NullString `json:"os"`
	Arch         sql.NullString `json:"arch"`
	AgentVersion sql.NullString `json:"agent_version"`
	Labels       sql.NullString `json:"labels"`
	Status       string         `json:"status"`
	LastSeenAt   sql.NullString `json:"last_seen_at"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

func (q *Queries) ListServers(ctx context.Context, arg ListServersParams) ([]ListServersRow, error) {
	rows, err := q.db.QueryContext(ctx, listServers, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServersRow{}
	for rows.Next() {
		var i ListServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.DisplayName,
			&i.IpAddress,
			&i.Os,
			&i.Arch,
			&i.AgentVersion,
			&i.Labels,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleServersOffline = `-- name: MarkStaleServersOffline :execrows
UPDATE servers
SET status = 'offline', updated_at = ?1
WHERE status = 'online' AND last_seen_at < ?2
`

type MarkStaleServersOfflineParams struct {
	UpdatedAt string         `json:"updated_at"`
	Cutoff    sql.NullString `json:"cutoff"`
}

func (q *Queries) MarkStaleServersOffline(ctx context.Context, arg MarkStaleServersOfflineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markStaleServersOffline, arg.UpdatedAt, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const registerServer = `-- name: RegisterServer :exec

INSERT INTO servers (id, hostname, display_name, ip_address, os, arch, agent_version, labels, status, last_seen_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type RegisterServerParams struct {
	ID           string         `json:"id"`
	Hostname     string         `json:"hostname"`
	DisplayName  sql.NullString `json:"display_name"`
	IpAddress    sql.NullString `json:"ip_address"`
	Os           sql.NullString `json:"os"`
	Arch         sql.NullString `json:"arch"`
	AgentVersion sql.NullString `json:"agent_version"`
	Labels       sql.NullString `json:"labels"`
	Status       string         `json:"status"`
	LastSeenAt   sql.NullString `json:"last_seen_at"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

// Servers: registered agent hosts reporting metrics to OpenTrace.
func (q *Queries) RegisterServer(ctx context.Context, arg RegisterServerParams) error {
	_, err := q.db.ExecContext(ctx, registerServer,
		arg.ID,
		arg.Hostname,
		arg.DisplayName,
		arg.IpAddress,
		arg.Os,
		arg.Arch,
		arg.AgentVersion,
		arg.Labels,
		arg.Status,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateServerDisplayName = `-- name: UpdateServerDisplayName :exec
UPDATE servers
SET display_name = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateServerDisplayNameParams struct {
	DisplayName sql.NullString `json:"display_name"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateServerDisplayName(ctx context.Context, arg UpdateServerDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateServerDisplayName, arg.DisplayName, arg.UpdatedAt, arg.ID)
	return err
}

const updateServerHeartbeat = `-- name: UpdateServerHeartbeat :execrows
UPDATE servers
SET status = 'online', last_seen_at = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateServerHeartbeatParams struct {
	LastSeenAt sql.NullString `json:"last_seen_at"`
	UpdatedAt  string         `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateServerHeartbeat(ctx context.Context, arg UpdateServerHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateServerHeartbeat, arg.LastSeenAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
