// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token, expires_at, created_at)
VALUES (?, ?, ?, ?, datetime('now'))
RETURNING id, user_id, token, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllSessionsForUser = `-- name: DeleteAllSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionsForUser, userID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execresult
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteExpiredSessions)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsByToken = `-- name: DeleteSessionsByToken :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSessionsByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByToken, token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token, expires_at, created_at FROM sessions WHERE token = ? AND expires_at > datetime('now')
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
