// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, user_id, token, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Token     string `json:"token"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

// Sessions: authentication session management.
// Queries for the sessions table.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllSessionsForUser = `-- name: DeleteAllSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?1
`

func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessionsForUser, userID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsByToken = `-- name: DeleteSessionsByToken :exec
DELETE FROM sessions WHERE token = ?1
`

func (q *Queries) DeleteSessionsByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByToken, token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token, expires_at, created_at
FROM sessions WHERE token = ?1 AND expires_at > ?2
`

type GetSessionByTokenParams struct {
	Token string `json:"token"`
	Now   string `json:"now"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, arg.Token, arg.Now)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
