// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_correlations.sql

package db

import (
	"context"
)

const getByFingerprint = `-- name: GetByFingerprint :one
SELECT id, service, error_fingerprint, error_class, source_file, endpoint,
       error_count, user_impact_score, investigation_count, priority_score,
       last_seen_at, created_at, updated_at
FROM uncovered_error_paths
WHERE error_fingerprint = ?1
`

func (q *Queries) GetByFingerprint(ctx context.Context, fingerprint string) (UncoveredErrorPath, error) {
	row := q.db.QueryRowContext(ctx, getByFingerprint, fingerprint)
	var i UncoveredErrorPath
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.ErrorFingerprint,
		&i.ErrorClass,
		&i.SourceFile,
		&i.Endpoint,
		&i.ErrorCount,
		&i.UserImpactScore,
		&i.InvestigationCount,
		&i.PriorityScore,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTopByPriority = `-- name: ListTopByPriority :many
SELECT id, service, error_fingerprint, error_class, source_file, endpoint,
       error_count, user_impact_score, investigation_count, priority_score,
       last_seen_at, created_at, updated_at
FROM uncovered_error_paths
ORDER BY priority_score DESC
LIMIT ?1
`

func (q *Queries) ListTopByPriority(ctx context.Context, maxResults int64) ([]UncoveredErrorPath, error) {
	rows, err := q.db.QueryContext(ctx, listTopByPriority, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UncoveredErrorPath{}
	for rows.Next() {
		var i UncoveredErrorPath
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.ErrorFingerprint,
			&i.ErrorClass,
			&i.SourceFile,
			&i.Endpoint,
			&i.ErrorCount,
			&i.UserImpactScore,
			&i.InvestigationCount,
			&i.PriorityScore,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopByPriorityForService = `-- name: ListTopByPriorityForService :many
SELECT id, service, error_fingerprint, error_class, source_file, endpoint,
       error_count, user_impact_score, investigation_count, priority_score,
       last_seen_at, created_at, updated_at
FROM uncovered_error_paths
WHERE service = ?1
ORDER BY priority_score DESC
LIMIT ?2
`

type ListTopByPriorityForServiceParams struct {
	Service    string `json:"service"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) ListTopByPriorityForService(ctx context.Context, arg ListTopByPriorityForServiceParams) ([]UncoveredErrorPath, error) {
	rows, err := q.db.QueryContext(ctx, listTopByPriorityForService, arg.Service, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UncoveredErrorPath{}
	for rows.Next() {
		var i UncoveredErrorPath
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.ErrorFingerprint,
			&i.ErrorClass,
			&i.SourceFile,
			&i.Endpoint,
			&i.ErrorCount,
			&i.UserImpactScore,
			&i.InvestigationCount,
			&i.PriorityScore,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneTestCorrelations = `-- name: PruneTestCorrelations :execrows
DELETE FROM uncovered_error_paths
WHERE rowid IN (
  SELECT u.rowid FROM uncovered_error_paths u WHERE u.updated_at < ?1 LIMIT 1000
)
`

func (q *Queries) PruneTestCorrelations(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneTestCorrelations, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshUncoveredPaths = `-- name: RefreshUncoveredPaths :exec

INSERT OR REPLACE INTO uncovered_error_paths
    (error_fingerprint, service, error_class, source_file, endpoint,
     error_count, user_impact_score, investigation_count, priority_score,
     last_seen_at, updated_at)
SELECT
    eg.fingerprint,
    COALESCE(eg.service, ''),
    COALESCE(eg.exception_class, ''),
    COALESCE(eg.source_file, ''),
    COALESCE(ce.entity_name, ''),
    eg.occurrence_count,
    COALESCE(eg.impact_score, 0.0),
    COALESCE(ce.investigation_count, 0),
    eg.occurrence_count * MAX(COALESCE(eg.impact_score, 1.0), 1.0) * (1 + COALESCE(ce.investigation_count, 0)),
    COALESCE(eg.last_seen_at, ?1),
    ?1
FROM error_groups eg
LEFT JOIN code_entities ce ON (
    ce.entity_type = 'endpoint'
    AND ce.service = eg.service
)
WHERE eg.status = 'unresolved'
  AND eg.occurrence_count >= 3
`

// Test correlations: uncovered error paths prioritized for test coverage.
// Table: uncovered_error_paths (migration 000043)
// NOTE: TopByPriority has two variants (with/without service filter).
func (q *Queries) RefreshUncoveredPaths(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, refreshUncoveredPaths, now)
	return err
}
