// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool_transitions.sql

package db

import (
	"context"
)

const incrementToolTransition = `-- name: IncrementToolTransition :exec

INSERT INTO tool_transitions (from_tool, to_tool, intent, total_count, last_seen_at)
VALUES (?1, ?2, ?3, 1, datetime('now'))
ON CONFLICT(from_tool, to_tool, intent) DO UPDATE SET
  total_count = total_count + 1,
  last_seen_at = datetime('now')
`

type IncrementToolTransitionParams struct {
	FromTool string `json:"from_tool"`
	ToTool   string `json:"to_tool"`
	Intent   string `json:"intent"`
}

// Tool transitions: pre-computed tool sequence statistics for ranking.
// Table: tool_transitions (migration 000040)
func (q *Queries) IncrementToolTransition(ctx context.Context, arg IncrementToolTransitionParams) error {
	_, err := q.db.ExecContext(ctx, incrementToolTransition, arg.FromTool, arg.ToTool, arg.Intent)
	return err
}

const incrementToolTransitionWithOutcome = `-- name: IncrementToolTransitionWithOutcome :exec
INSERT INTO tool_transitions (from_tool, to_tool, intent, total_count, resolved_count, abandoned_count, last_seen_at)
VALUES (?1, ?2, ?3, 1,
        ?4, ?5, datetime('now'))
ON CONFLICT(from_tool, to_tool, intent) DO UPDATE SET
  total_count = total_count + 1,
  resolved_count = resolved_count + sqlc.arg(resolved_inc),
  abandoned_count = abandoned_count + sqlc.arg(abandoned_inc),
  last_seen_at = datetime('now')
`

type IncrementToolTransitionWithOutcomeParams struct {
	FromTool     string `json:"from_tool"`
	ToTool       string `json:"to_tool"`
	Intent       string `json:"intent"`
	ResolvedInc  int64  `json:"resolved_inc"`
	AbandonedInc int64  `json:"abandoned_inc"`
}

func (q *Queries) IncrementToolTransitionWithOutcome(ctx context.Context, arg IncrementToolTransitionWithOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, incrementToolTransitionWithOutcome,
		arg.FromTool,
		arg.ToTool,
		arg.Intent,
		arg.ResolvedInc,
		arg.AbandonedInc,
	)
	return err
}

const pruneToolTransitions = `-- name: PruneToolTransitions :execrows
DELETE FROM tool_transitions WHERE last_seen_at < ?1
`

func (q *Queries) PruneToolTransitions(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneToolTransitions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
