// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: traces.sql

package db

import (
	"context"
	"database/sql"
)

const countTraceStatuses = `-- name: CountTraceStatuses :one
SELECT COUNT(*) FROM trace_status
`

func (q *Queries) CountTraceStatuses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTraceStatuses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTraceStatusByID = `-- name: GetTraceStatusByID :one

SELECT trace_id, span_count, root_span_id, services,
       first_seen_at, last_updated_at, duration_ms, status, has_errors
FROM trace_status WHERE trace_id = ?1
`

// Traces: distributed trace reassembly status tracking.
// Table: trace_status (migration 000037)
// NOTE: UpsertTraceStatus in the Go code uses a transaction with read-modify-write
// for services list merging. The insert/update below are the individual SQL statements
// used within that transaction.
func (q *Queries) GetTraceStatusByID(ctx context.Context, traceID string) (TraceStatus, error) {
	row := q.db.QueryRowContext(ctx, getTraceStatusByID, traceID)
	var i TraceStatus
	err := row.Scan(
		&i.TraceID,
		&i.SpanCount,
		&i.RootSpanID,
		&i.Services,
		&i.FirstSeenAt,
		&i.LastUpdatedAt,
		&i.DurationMs,
		&i.Status,
		&i.HasErrors,
	)
	return i, err
}

const insertTraceStatus = `-- name: InsertTraceStatus :exec
INSERT INTO trace_status (trace_id, span_count, root_span_id, services,
                          first_seen_at, last_updated_at, duration_ms, status, has_errors)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7,
        ?8, ?9)
`

type InsertTraceStatusParams struct {
	TraceID       string         `json:"trace_id"`
	SpanCount     int64          `json:"span_count"`
	RootSpanID    sql.NullString `json:"root_span_id"`
	Services      string         `json:"services"`
	FirstSeenAt   string         `json:"first_seen_at"`
	LastUpdatedAt string         `json:"last_updated_at"`
	DurationMs    float64        `json:"duration_ms"`
	Status        string         `json:"status"`
	HasErrors     int64          `json:"has_errors"`
}

func (q *Queries) InsertTraceStatus(ctx context.Context, arg InsertTraceStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertTraceStatus,
		arg.TraceID,
		arg.SpanCount,
		arg.RootSpanID,
		arg.Services,
		arg.FirstSeenAt,
		arg.LastUpdatedAt,
		arg.DurationMs,
		arg.Status,
		arg.HasErrors,
	)
	return err
}

const listRecentTraces = `-- name: ListRecentTraces :many
SELECT trace_id, span_count, root_span_id, services,
       first_seen_at, last_updated_at, duration_ms, status, has_errors
FROM trace_status
ORDER BY last_updated_at DESC
LIMIT ?2 OFFSET ?1
`

type ListRecentTracesParams struct {
	ResultsOffset int64 `json:"results_offset"`
	MaxResults    int64 `json:"max_results"`
}

func (q *Queries) ListRecentTraces(ctx context.Context, arg ListRecentTracesParams) ([]TraceStatus, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTraces, arg.ResultsOffset, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraceStatus{}
	for rows.Next() {
		var i TraceStatus
		if err := rows.Scan(
			&i.TraceID,
			&i.SpanCount,
			&i.RootSpanID,
			&i.Services,
			&i.FirstSeenAt,
			&i.LastUpdatedAt,
			&i.DurationMs,
			&i.Status,
			&i.HasErrors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleTraces = `-- name: MarkStaleTraces :execrows
UPDATE trace_status SET status = 'timeout'
WHERE status = 'partial' AND last_updated_at < ?1
`

func (q *Queries) MarkStaleTraces(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markStaleTraces, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTraceStatus = `-- name: UpdateTraceStatus :exec
UPDATE trace_status
SET span_count = ?1,
    root_span_id = ?2,
    services = ?3,
    last_updated_at = ?4,
    duration_ms = ?5,
    has_errors = ?6
WHERE trace_id = ?7
`

type UpdateTraceStatusParams struct {
	SpanCount     int64          `json:"span_count"`
	RootSpanID    sql.NullString `json:"root_span_id"`
	Services      string         `json:"services"`
	LastUpdatedAt string         `json:"last_updated_at"`
	DurationMs    float64        `json:"duration_ms"`
	HasErrors     int64          `json:"has_errors"`
	TraceID       string         `json:"trace_id"`
}

func (q *Queries) UpdateTraceStatus(ctx context.Context, arg UpdateTraceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTraceStatus,
		arg.SpanCount,
		arg.RootSpanID,
		arg.Services,
		arg.LastUpdatedAt,
		arg.DurationMs,
		arg.HasErrors,
		arg.TraceID,
	)
	return err
}
