// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trends.sql

package db

import (
	"context"
)

const listDeployMarkersByServiceSince = `-- name: ListDeployMarkersByServiceSince :many
SELECT id, service, environment, commit_hash, first_seen_at, request_count
FROM deploy_markers
WHERE first_seen_at >= ?1 AND service = ?2
ORDER BY first_seen_at ASC
`

type ListDeployMarkersByServiceSinceParams struct {
	Since   string `json:"since"`
	Service string `json:"service"`
}

func (q *Queries) ListDeployMarkersByServiceSince(ctx context.Context, arg ListDeployMarkersByServiceSinceParams) ([]DeployMarker, error) {
	rows, err := q.db.QueryContext(ctx, listDeployMarkersByServiceSince, arg.Since, arg.Service)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployMarker{}
	for rows.Next() {
		var i DeployMarker
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Environment,
			&i.CommitHash,
			&i.FirstSeenAt,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployMarkersSince = `-- name: ListDeployMarkersSince :many
SELECT id, service, environment, commit_hash, first_seen_at, request_count
FROM deploy_markers
WHERE first_seen_at >= ?1
ORDER BY first_seen_at ASC
`

func (q *Queries) ListDeployMarkersSince(ctx context.Context, since string) ([]DeployMarker, error) {
	rows, err := q.db.QueryContext(ctx, listDeployMarkersSince, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployMarker{}
	for rows.Next() {
		var i DeployMarker
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Environment,
			&i.CommitHash,
			&i.FirstSeenAt,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDeployMarkers = `-- name: PruneDeployMarkers :execrows
DELETE FROM deploy_markers WHERE first_seen_at < ?1
`

func (q *Queries) PruneDeployMarkers(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneDeployMarkers, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneTrendBuckets = `-- name: PruneTrendBuckets :execrows

DELETE FROM metric_buckets WHERE bucket_start < ?1
`

// Trends: metric buckets, deploy markers, and time-series data.
// Only STATIC queries here; aggregation and dynamic queries use squirrel.
func (q *Queries) PruneTrendBuckets(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneTrendBuckets, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
