// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watches.sql

package db

import (
	"context"
	"database/sql"
)

const acknowledgeWatchAlert = `-- name: AcknowledgeWatchAlert :execrows
UPDATE watch_alerts SET status = 'acknowledged' WHERE id = ?1
`

func (q *Queries) AcknowledgeWatchAlert(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeWatchAlert, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeWatchRun = `-- name: CompleteWatchRun :execrows
UPDATE watch_runs SET status = 'completed', metric_value = ?1, breached = ?2,
    summary = ?3, finished_at = ?4 WHERE id = ?5
`

type CompleteWatchRunParams struct {
	MetricValue sql.NullFloat64 `json:"metric_value"`
	Breached    int64           `json:"breached"`
	Summary     sql.NullString  `json:"summary"`
	FinishedAt  sql.NullString  `json:"finished_at"`
	ID          string          `json:"id"`
}

func (q *Queries) CompleteWatchRun(ctx context.Context, arg CompleteWatchRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeWatchRun,
		arg.MetricValue,
		arg.Breached,
		arg.Summary,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPendingAlerts = `-- name: CountPendingAlerts :one
SELECT COUNT(*) FROM watch_alerts WHERE status = 'pending'
`

func (q *Queries) CountPendingAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWatch = `-- name: CreateWatch :exec

INSERT INTO watches (id, metric, operator, threshold, service, endpoint, environment, commit_hash,
    duration, urgency, check_interval, baseline_window, min_consecutive, status,
    consecutive_breaches, expires_at, created_by, session_id, next_check_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, ?12,
    ?13, ?14, 0,
    ?15, ?16, ?17, ?18,
    ?19, ?20)
`

type CreateWatchParams struct {
	ID             string         `json:"id"`
	Metric         string         `json:"metric"`
	Operator       string         `json:"operator"`
	Threshold      float64        `json:"threshold"`
	Service        string         `json:"service"`
	Endpoint       string         `json:"endpoint"`
	Environment    string         `json:"environment"`
	CommitHash     string         `json:"commit_hash"`
	Duration       string         `json:"duration"`
	Urgency        string         `json:"urgency"`
	CheckInterval  string         `json:"check_interval"`
	BaselineWindow string         `json:"baseline_window"`
	MinConsecutive int64          `json:"min_consecutive"`
	Status         string         `json:"status"`
	ExpiresAt      sql.NullString `json:"expires_at"`
	CreatedBy      string         `json:"created_by"`
	SessionID      string         `json:"session_id"`
	NextCheckAt    sql.NullString `json:"next_check_at"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

// Watches: agent-first metric + operator + threshold monitoring.
// Queries for watches, watch_runs, and watch_alerts tables.
func (q *Queries) CreateWatch(ctx context.Context, arg CreateWatchParams) error {
	_, err := q.db.ExecContext(ctx, createWatch,
		arg.ID,
		arg.Metric,
		arg.Operator,
		arg.Threshold,
		arg.Service,
		arg.Endpoint,
		arg.Environment,
		arg.CommitHash,
		arg.Duration,
		arg.Urgency,
		arg.CheckInterval,
		arg.BaselineWindow,
		arg.MinConsecutive,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.SessionID,
		arg.NextCheckAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWatchAlert = `-- name: CreateWatchAlert :exec

INSERT INTO watch_alerts (id, watch_id, run_id, urgency, summary, trigger_metric, trigger_value, threshold_value, evidence_json, status, created_at)
VALUES (?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9, 'pending', ?10)
`

type CreateWatchAlertParams struct {
	ID             string         `json:"id"`
	WatchID        string         `json:"watch_id"`
	RunID          sql.NullString `json:"run_id"`
	Urgency        string         `json:"urgency"`
	Summary        string         `json:"summary"`
	TriggerMetric  string         `json:"trigger_metric"`
	TriggerValue   float64        `json:"trigger_value"`
	ThresholdValue float64        `json:"threshold_value"`
	EvidenceJson   sql.NullString `json:"evidence_json"`
	CreatedAt      string         `json:"created_at"`
}

// ---- Watch Alerts ----
func (q *Queries) CreateWatchAlert(ctx context.Context, arg CreateWatchAlertParams) error {
	_, err := q.db.ExecContext(ctx, createWatchAlert,
		arg.ID,
		arg.WatchID,
		arg.RunID,
		arg.Urgency,
		arg.Summary,
		arg.TriggerMetric,
		arg.TriggerValue,
		arg.ThresholdValue,
		arg.EvidenceJson,
		arg.CreatedAt,
	)
	return err
}

const createWatchRun = `-- name: CreateWatchRun :exec


INSERT INTO watch_runs (id, watch_id, status, started_at) VALUES (?1, ?2, 'running', ?3)
`

type CreateWatchRunParams struct {
	ID        string `json:"id"`
	WatchID   string `json:"watch_id"`
	StartedAt string `json:"started_at"`
}

// DYNAMIC: use squirrel for ListWatches with optional status/service/session_id filters
// ---- Watch Runs ----
func (q *Queries) CreateWatchRun(ctx context.Context, arg CreateWatchRunParams) error {
	_, err := q.db.ExecContext(ctx, createWatchRun, arg.ID, arg.WatchID, arg.StartedAt)
	return err
}

const deleteWatch = `-- name: DeleteWatch :execrows
DELETE FROM watches WHERE id = ?1
`

func (q *Queries) DeleteWatch(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWatch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dismissWatchAlert = `-- name: DismissWatchAlert :execrows
UPDATE watch_alerts SET status = 'dismissed', dismiss_reason = ?1 WHERE id = ?2
`

type DismissWatchAlertParams struct {
	DismissReason sql.NullString `json:"dismiss_reason"`
	ID            string         `json:"id"`
}

func (q *Queries) DismissWatchAlert(ctx context.Context, arg DismissWatchAlertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissWatchAlert, arg.DismissReason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireWatches = `-- name: ExpireWatches :execrows
UPDATE watches SET status = 'expired', updated_at = ?1
WHERE expires_at IS NOT NULL AND expires_at <= ?1 AND status = 'active'
`

func (q *Queries) ExpireWatches(ctx context.Context, now string) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireWatches, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failWatchRun = `-- name: FailWatchRun :execrows
UPDATE watch_runs SET status = 'failed', error_message = ?1, finished_at = ?2 WHERE id = ?3
`

type FailWatchRunParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	FinishedAt   sql.NullString `json:"finished_at"`
	ID           string         `json:"id"`
}

func (q *Queries) FailWatchRun(ctx context.Context, arg FailWatchRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failWatchRun, arg.ErrorMessage, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDueWatches = `-- name: GetDueWatches :many
SELECT id, metric, operator, threshold, service, endpoint, environment, commit_hash,
    duration, urgency, check_interval, baseline_window, min_consecutive, status,
    baseline_json, consecutive_breaches, current_value, expires_at, created_by,
    session_id, last_checked_at, next_check_at, created_at, updated_at
FROM watches
WHERE status = 'active' AND next_check_at IS NOT NULL AND next_check_at <= ?1
ORDER BY next_check_at ASC
`

func (q *Queries) GetDueWatches(ctx context.Context, now sql.NullString) ([]Watch, error) {
	rows, err := q.db.QueryContext(ctx, getDueWatches, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Watch{}
	for rows.Next() {
		var i Watch
		if err := rows.Scan(
			&i.ID,
			&i.Metric,
			&i.Operator,
			&i.Threshold,
			&i.Service,
			&i.Endpoint,
			&i.Environment,
			&i.CommitHash,
			&i.Duration,
			&i.Urgency,
			&i.CheckInterval,
			&i.BaselineWindow,
			&i.MinConsecutive,
			&i.Status,
			&i.BaselineJson,
			&i.ConsecutiveBreaches,
			&i.CurrentValue,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.SessionID,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatch = `-- name: GetWatch :one
SELECT id, metric, operator, threshold, service, endpoint, environment, commit_hash,
    duration, urgency, check_interval, baseline_window, min_consecutive, status,
    baseline_json, consecutive_breaches, current_value, expires_at, created_by,
    session_id, last_checked_at, next_check_at, created_at, updated_at
FROM watches WHERE id = ?1
`

func (q *Queries) GetWatch(ctx context.Context, id string) (Watch, error) {
	row := q.db.QueryRowContext(ctx, getWatch, id)
	var i Watch
	err := row.Scan(
		&i.ID,
		&i.Metric,
		&i.Operator,
		&i.Threshold,
		&i.Service,
		&i.Endpoint,
		&i.Environment,
		&i.CommitHash,
		&i.Duration,
		&i.Urgency,
		&i.CheckInterval,
		&i.BaselineWindow,
		&i.MinConsecutive,
		&i.Status,
		&i.BaselineJson,
		&i.ConsecutiveBreaches,
		&i.CurrentValue,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.SessionID,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchAlert = `-- name: GetWatchAlert :one
SELECT id, watch_id, run_id, urgency, summary, trigger_metric, trigger_value,
    threshold_value, evidence_json, status, dismiss_reason, created_at
FROM watch_alerts WHERE id = ?1
`

func (q *Queries) GetWatchAlert(ctx context.Context, id string) (WatchAlert, error) {
	row := q.db.QueryRowContext(ctx, getWatchAlert, id)
	var i WatchAlert
	err := row.Scan(
		&i.ID,
		&i.WatchID,
		&i.RunID,
		&i.Urgency,
		&i.Summary,
		&i.TriggerMetric,
		&i.TriggerValue,
		&i.ThresholdValue,
		&i.EvidenceJson,
		&i.Status,
		&i.DismissReason,
		&i.CreatedAt,
	)
	return i, err
}

const listWatchRuns = `-- name: ListWatchRuns :many
SELECT id, watch_id, status, metric_value, breached, summary, error_message, started_at, finished_at
FROM watch_runs WHERE watch_id = ?1 ORDER BY started_at DESC LIMIT ?2
`

type ListWatchRunsParams struct {
	WatchID  string `json:"watch_id"`
	RowLimit int64  `json:"row_limit"`
}

func (q *Queries) ListWatchRuns(ctx context.Context, arg ListWatchRunsParams) ([]WatchRun, error) {
	rows, err := q.db.QueryContext(ctx, listWatchRuns, arg.WatchID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchRun{}
	for rows.Next() {
		var i WatchRun
		if err := rows.Scan(
			&i.ID,
			&i.WatchID,
			&i.Status,
			&i.MetricValue,
			&i.Breached,
			&i.Summary,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWatchAfterCheck = `-- name: UpdateWatchAfterCheck :execrows
UPDATE watches SET current_value = ?1, consecutive_breaches = ?2,
    last_checked_at = ?3, next_check_at = ?4, updated_at = ?5
WHERE id = ?6
`

type UpdateWatchAfterCheckParams struct {
	CurrentValue        sql.NullFloat64 `json:"current_value"`
	ConsecutiveBreaches int64           `json:"consecutive_breaches"`
	LastCheckedAt       sql.NullString  `json:"last_checked_at"`
	NextCheckAt         sql.NullString  `json:"next_check_at"`
	UpdatedAt           string          `json:"updated_at"`
	ID                  string          `json:"id"`
}

func (q *Queries) UpdateWatchAfterCheck(ctx context.Context, arg UpdateWatchAfterCheckParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWatchAfterCheck,
		arg.CurrentValue,
		arg.ConsecutiveBreaches,
		arg.LastCheckedAt,
		arg.NextCheckAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWatchBaseline = `-- name: UpdateWatchBaseline :execrows
UPDATE watches SET baseline_json = ?1, updated_at = ?2 WHERE id = ?3
`

type UpdateWatchBaselineParams struct {
	BaselineJson sql.NullString `json:"baseline_json"`
	UpdatedAt    string         `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateWatchBaseline(ctx context.Context, arg UpdateWatchBaselineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWatchBaseline, arg.BaselineJson, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWatchStatus = `-- name: UpdateWatchStatus :execrows
UPDATE watches SET status = ?1, updated_at = ?2 WHERE id = ?3
`

type UpdateWatchStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateWatchStatus(ctx context.Context, arg UpdateWatchStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWatchStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
