// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_templates.sql

package db

import (
	"context"
)

const getWorkflowByName = `-- name: GetWorkflowByName :many
SELECT id, intent, name, step_order, tool_name, args_hint, source, resolved_session_count, created_at
FROM workflow_templates
WHERE name = ?1
ORDER BY step_order
`

func (q *Queries) GetWorkflowByName(ctx context.Context, name string) ([]WorkflowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getWorkflowByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTemplate{}
	for rows.Next() {
		var i WorkflowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Intent,
			&i.Name,
			&i.StepOrder,
			&i.ToolName,
			&i.ArgsHint,
			&i.Source,
			&i.ResolvedSessionCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowNextStep = `-- name: GetWorkflowNextStep :many

SELECT id, intent, name, step_order, tool_name, args_hint, source, resolved_session_count, created_at
FROM workflow_templates
WHERE intent = ?1 AND step_order = ?2
ORDER BY resolved_session_count DESC
`

type GetWorkflowNextStepParams struct {
	Intent    string `json:"intent"`
	StepOrder int64  `json:"step_order"`
}

// Workflow templates: curated and learned tool sequences for investigation intents.
// Table: workflow_templates (migration 000040)
func (q *Queries) GetWorkflowNextStep(ctx context.Context, arg GetWorkflowNextStepParams) ([]WorkflowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getWorkflowNextStep, arg.Intent, arg.StepOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTemplate{}
	for rows.Next() {
		var i WorkflowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Intent,
			&i.Name,
			&i.StepOrder,
			&i.ToolName,
			&i.ArgsHint,
			&i.Source,
			&i.ResolvedSessionCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTemplates = `-- name: ListWorkflowTemplates :many
SELECT id, intent, name, step_order, tool_name, args_hint, source, resolved_session_count, created_at
FROM workflow_templates
WHERE intent = ?1
ORDER BY name, step_order
`

func (q *Queries) ListWorkflowTemplates(ctx context.Context, intent string) ([]WorkflowTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowTemplates, intent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTemplate{}
	for rows.Next() {
		var i WorkflowTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Intent,
			&i.Name,
			&i.StepOrder,
			&i.ToolName,
			&i.ArgsHint,
			&i.Source,
			&i.ResolvedSessionCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
